### ISSUE TITLE
Enhancements on Facades

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#102]
I love facades, but there is a couple of issues with their current implementation :
1. **They don't have their own installer.** Instead, they have an `Action<DiContainer>` which cannot be injected and therefore will have to sit somewhere inside another installer in the case injection is needed (like provided prefabs). It would be nice if they could use their own injected installer, to be on equal foot with how the root `DiContainer` is setup.
2. **They can't be placed in the scene in the editor and properly injected when the app starts.** Their dependencies will be injected only from the `DiContainer` defined in the global installers, I am not aware of any workaround. I created some enemies using a facade, but I had to _unzenject_ them once I realized that limitation, as I usually place instances of my enemies in the scene for quick prototyping.

Here are the steps which I propose to resolve the second problem:
1. Add a kind of `FacadeBehaviour` class which the user can add to the root gameObject of their prefab, this class will accept a (or list of) `MonoInstaller` to setup the facade.
2. Zenject will detect those class when injecting the scene's gameObjects at startup, create the corresponding Facade for each of them.

Extra bonus: For a really needed conveniency, whenever Zenject instantiates a prefab, it looks for this class as well and Facade-inject them in the same way.

I hope those changes to be added in v4.0 (#100).

**Comment by svermeulen** [comment]
Completely agree - we need some kind of `FacadeCompositionRoot`.  The current facade stuff works well when using non-monobehaviour classes, but has limitations otherwise.  Being able to drop facades into your scene at edit time is a pretty common requirement for example and is very awkward currently, as you say.

**Comment by green-coder** [comment]
Hi, I saw that you started committing some code for improving the facades. I am looking forward to test this part as soon as it becomes stable, and will be happy to provide you feedback.

**Comment by svermeulen** [comment]
Absolutely, yeah, that would be great.  I'll let you know, just want to make a few more adjustments to it

**Comment by svermeulen** [comment]
Ok you can take a look now.  Take a look at the commit messages in develop to see what's changed.  Nothing is really documented yet.

Also I started making an example here:  (didn't get that far though)
https://dl.dropboxusercontent.com/u/2959315/temp/FacadeTest.zip

The example shows how to create MonoBehaviour facades dynamically, and also shows how to drop them into your scene at the start too.

Let me know if you have any thoughts on it.

**Comment by green-coder** [comment]
Thank you. I will try to take a look at it within the next 48 hours.

**Comment by green-coder** [comment]
I took a look at the commits and the FacadeTest sample, and here is my first feedback. Keep in mind that it is just my own opinion, it may not be represent the other users.
1. Your example is too complex with respect to real world usage as game developers don't have time to write so much code as in your example and spend so much time organizing everything. They probably will suffer a lot when reading it and many might feel lost and may never use the feature that the example originally tries to illustrate. Non-hardcore users don't listen at all your recommendations and mostly always go for the easiest way. For example:
   - They don't use constructors, they use the `Inject` attribute instead (because it is faster to write and to change).
   - They don't use ITicker, they use the Update() function of Unity.
   - They don't have 1 class to initialize another one.
   - They don't use the facade as a way to hide the inner mechanism of a group of `GameObject`, they use it just for the `subContainer`, where we can define and inject singletons which are local to a prefab.
   - They keep their `RigidBody`, `Collider`, and their `MyCharacterController` together at the root of their prefab.
   - Even for me it is difficult to understand what is going on in the example.
2. What `ZenjectBinding` is doing is not clear to me, the comment in the class need improvements.I am puzzled as why the `EnemyFacade` (which is a `MonoBehaviour`) can have a constructor. I don't know who calls it.
3. I remember seeing somewhere that the components on the GameObject of the `FacadeCompositionRoot` are not injected, I don't understand why. I also don't understand why only the direct children are injected (and not all the descendants).

In a few days, I will try to use this version of Zenject on a simple example which I will write from scratch, and I hope to give you additional feedback.

**Comment by svermeulen** [comment]
Thanks.  You make some good points.

1 - Yeah, it's tough to make an example that is small enough to be accessible but not so small that it's not interesting.

This example is closer to like a complete sample game.  I think it's still useful to have complete projects (like the Asteroids game) so maybe the solution would be to also have simple demos that strictly show the feature and that's it.

Also, I don't see a problem with using what I consider good practices in the example, even if most people don't follow them.  Using constructors or [PostInject] is better than using [Inject], even though yes it is more work.

It sounds like you are saying that I should create the example in a way that is most applicable to the average Zenject user, based on the way they prefer to use Zenject rather than the way I prefer to do it.  That makes total sense, but honestly I have a hard time doing that.

For example, I don't like making everything MonoBehaviour's.  I prefer to make something a MonoBehaviour only when there's a reason to do so - like if it hooks into Unity events like OnCollisionEnter, or if it represents a 3D object in the scene and so it makes sense to have a transform, etc.

You're right this probably does alienate some users but again, it's hard for me to break this practice.

2 - Good call - I'll add some comments to ZenjectBinding.  It's just used as a shortcut to dragging references in your scene into the inspector properties of a MonoInstaller, so they can be hooked into the container.  Using ZenjectBinding it will automatically be added to your Container.  It's a new feature that I'm playing with but so far I like it, even though it does have some drawbacks (like the fact that it's somewhat 'hidden' - you have to find the bindings in the scene rather than just looking at the code in installers)

Also, yes, that EnemyFacade constructor is a bug  :)

3 - Right now how it works is that the root of the facade (the game object with FacadeCompositionRoot) gets injected using the parent container, and it's only the objects underneath that (all objects, not just direct children) that get injected using the sub container.  However, I think you're right that it would probably be better to inject the root object (the game object with FacadeCompositionRoot) using the sub container as well.  This would allow you to actually have your facade class at the root

I agree that the rigidbody etc. should also be at the root.

Let me make those adjustments before you try making your own example from scratch.   Btw that would be great to share as well!  Would be good to offer several different opinionated approaches to this

**Comment by svermeulen** [comment]
Ok I made that change to facade and fixed a few other things.  Now, the components beside the FacadeCompositionRoot are treated as "inside" the subcontainer.

I also made a bunch of adjustments to the sample, and committed it to the Zenject repo alongside the existing asteroids demo, in the folder "Sample2".  I still need to clean it up and add comments, etc.

So feel free to give it a go and let me know if you hit any issues or have any questions.

**Comment by green-coder** [comment]
Thank you. I will give it a try within 48 hours.

For the examples, there is no need to choose between showing what people can do without directly depending on the MonoBehaviour and what people are most likely to digest. You can include multiple examples, each of them showing a given set of features, with some example described as a show case of how to build a game the way you are used to.

Later, I hope to find the time to help you writing some of the examples.

**Comment by green-coder** [comment]
Busy ATM, I hope to test it before next Monday.

**Comment by svermeulen** [comment]
Ok thanks

**Comment by slimshader** [comment]
I looked over documentation for new FacadeCompositionRoot and it looks fantastic. What is the eta on 4.0?

**Comment by svermeulen** [comment]
Should be pretty soon - like a week or two.

I was about to release v4.0 at the same time I updated the documentation, but then realized there were several more changes I wanted to make to it, and since several of these are API breaking changes, I figured it was better to do them all at once and avoid breaking things for people multiple times.

**Comment by svermeulen** [comment]
I think Zenject 4 addresses all these issues  - if not feel free to open another issue.  I also added integration tests that can be used to see how each individual feature works in isolation.  

Documentation still needs updating however
