### ISSUE TITLE
`Assets/Create/Zenject/Project Composition Root` Fails to create the prefab.

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#113]
The menu item shown in the title fails to create the prefab in the resources directory.

Error messages
http://puu.sh/oBPRK/cfaf46d70c.png
http://puu.sh/oBPVw/51c590fa3e.png

My observations are that somewhere along the line, the full file path is being obtained and used (based on the full file path shown in the above screen shots) when it should probably be just the `Assets/Resources/...`.

As an additional note, the new `Edit/Zenject/Create Project Composition Root` menu option works for me.

**Comment by svermeulen** [comment]
Yep, that was exactly right, it was using the full path rather than the relative one that Unity wants.  Thanks!  Fixed now.

Let me know if you have any more feedback on Zenject 4 - currently only a few teams have used it.  I really need to update the documentation for the changes, but otherwise it should be ready to merge back into master
