### ISSUE TITLE
BindGameObjectFactory Transform in addition to string parameter

### ISSUE THREAD

**Issue by HatiGamedev** [ssannandeji/Zenject-2019#114]
I suggest another overload with second optional parameter as transform in addition to the string overload?

I personally find string very obscure and can lead to critical bugs.

**Comment by svermeulen** [comment]
You mean for the "groupName" parameter?  I agree that the string parameter here is confusing.  This is more obvious in Zenject 4 (develop branch) which gives the group name parameter its own method:

```
    Container.BindFactory<Explosion, Explosion.Factory>().FromPrefab(_settings.ExplosionPrefab).UnderGameObjectGroup("Explosions");
```

The naming could still be better though.  Not totally sold on the name `UnderGameObjectGroup`.  Maybe `UnderTransform(transform)` and a string overload `UnderTransform("Explosions")`?

**Comment by HatiGamedev** [comment]
Yeah i refered to the groupname parameter. 
Sounds good in Zenject 4 :+1:

**Comment by HatiGamedev** [comment]
To clarify things

My special usecase is for dynamic UI - so I cannot use an Anchor/Vertical Layout Rect directly, because currently the grouping is root level only. So the easiest fix would be allowing to use Transforms as parameter.

**Comment by svermeulen** [comment]
If you have requirements like that, you might want to just create a custom factory class that handles setting up the proper transform parent.  Your custom factory could call the game object factory create(), set the parent, and return that

**Comment by HatiGamedev** [comment]
That's what I did actually :) but since there was this grouping feature I thought it would be a nice and easy addition

**Comment by 4xisblack** [comment]
I'm looking into similar issues at the moment! While custom factories do work to an extent, the problem is that sometimes I like to have bindings that depend on the instantiated object's position within the hierarchy (a position which cannot currently be set prior to field/method injection except, I suppose, through gameobject groups).

I think I'd be in favour of some sort of .UnderTransform() specifier (perhaps taking a Func<Context Transform> as an argument, so that we can use the InjectContext to determine where to parent stuff?). But I think the more important feature would be permitting IInstantiator to accept a parent transform as arguments to its various gameobject-based methods.

**Comment by svermeulen** [comment]
Why do you need to pass in the parent to the IInstantiator methods?  Is that different from calling Instantiate and then immediately calling transform.SetParent afterwards?

**Comment by 4xisblack** [comment]
We use bindings along the lines of:

`Container.Bind<Collider>().FromComponentInParent();`

On rare occasions we would even use a FromComponentsInChildren() type thing.

This works within a scene, or within a prefab, and it's a very powerful pattern (my level designers love thinking in terms of parent/child relationships!). If however we instantiate a prefab at runtime which requires a Collider—and said Collider resides in the gameobject to which we want to parent said prefab—such a binding strategy becomes nonviable without creating a whole bunch of subcontainers.

The order right now can only be: 1) UnityEngine.Object.Instantiate, 2) InjectFields, 3) SetParent. I'm interested in deferring the injection step so that it goes 1) Instantiate a bunch of things 2) Parent those things together, 3) InjectFields.

In the past I've actually done this by calling InjectFields myself, manually, after setting up the transform hierarchy, but this requires a bunch of boilerplate on my end that I no longer wish to maintain given the furious pace at which this framework improves :D so I've been considering abandoning the strategy entirely.

**Comment by svermeulen** [comment]
Oh ok that makes sense now.  I see why you can't just apply the parent afterwards.

I agree - we should add an optional `Transform` parameter to use as the parent for the Instantiate methods that create game objects, and also add `UnderTransform` methods to give either a transform or a `Func<Transform>`

**Comment by svermeulen** [comment]
Added UnderTransform methods and renamed WithGameObjectGroup to UnderTransformGroup
