### ISSUE TITLE
[PostInject] method getting called twice.

### ISSUE THREAD

**Issue by prestoncmatterport** [ssannandeji/Zenject-2019#116]
Calling .ToSingleGameObject(), then calling .Resolve(), results in the [PostInject] method getting called twice.

**Comment by svermeulen** [comment]
I'm guessing this is because you are calling `.Resolve()` inside your installer.  The way Zenject is designed, you should not resolve dependencies until after the install phase.  Otherwise, Zenject will not know which game objects have already been injected.

In other words, if you move your call to `Resolve()` to a `Start` method, or use an `IInitializable`, then your `[PostInject]` should only be called once.  Or, ideally, don't call `Resolve()` and instead use `[Inject]` / constructor params / post inject params / etc.

**Comment by prestoncmatterport** [comment]
Ah, I see.  Thank you for clearing that up for me. :)
I would suggest adding that info about .Resolve() not belonging in an installer to the Readme.

**Comment by svermeulen** [comment]
True, this would be perfect for the "Gotchas" section

**Comment by svermeulen** [comment]
I actually ended up fixing this issue with the most recent commit.  Even though it's not good practice, it should be supported.  If you update the PostInject will only be called once now.

**Comment by prestoncmatterport** [comment]
Awesome, thank you! :)
