### ISSUE TITLE
Is it possible to initialize the container outside of a MonoInstaller?

### ISSUE THREAD

**Issue by nehmebilal** [ssannandeji/Zenject-2019#118]
Hi,

I am developing a unity application where the Ui is built in XAML. The XAML context is initialized first and then Unity is loaded. I would like to pass a dependency down from XAML context to the Unity context. The problem is that the DiContainer is created in the `MonoInstaller` and at that point, it's too late. Ideally, I would be able to access the container before the Unity context is loaded and bind the dependencies that I need to pass down there.

Is there a clean way to achieve this?

Thanks!

**Comment by svermeulen** [comment]
When loading another scene in Unity, and you want to add information to the next scene's container, this is done using `ZenUtil.LoadScene` which takes an `Action<DiContainer>` callback that allows you to add dependencies to the container.  (details [here](https://github.com/modesttree/Zenject#injecting-data-across-scenes)). Could that also work in this case?

**Comment by nehmebilal** [comment]
Hmm close but unfortunately I'm not manually loading the scene. Unity generates code for UWP that automatically loads the Unity window after initializing the XAML app.

**Comment by svermeulen** [comment]
I'm not familiar with using XAML with Unity.  So you're saying that you have some C# code executed before Unity initializes the scene, and you have some objects there that you'd like to add to Zenject so that you can reference it from classes that initialize with the scene?

The way Zenject works is that every scene has a SceneCompositionRoot, which has its own DiContainer.  These containers have a parent container, that is created by the ProjectCompositionRoot (or GlobalCompositionRoot as referred to in Zenject 3).  Every container inherits all the dependencies that exist within its parent containers.

So it's tempting to add your objects to the ProjectCompositionRoot's container.  Then every dependency in any scene could access these objects.  However this also wouldn't work since the ProjectCompositionRoot needs a unity scene to exist for it to initialize properly.  So maybe the cleanest way to achieve what you want here is to add another layer above this, something like 'StaticCompositionRoot', which would be the parent of the ProjectCompositionRoot's container.  Then, all you would need is access to the Zenject assembly and you could add your objects there.  Again, I don't know how XAML + UWP + Unity works really - but that's just one thought I had

**Comment by nehmebilal** [comment]
That makes sense! Can you explain more how to create the `StaticCompositionRoot` and make it a parent of the `ProjectCompositionRoot`?

**Comment by svermeulen** [comment]
Try adding this file next to `GlobalCompositionRoot`:

```
namespace Zenject
{
    public static class StaticCompositionRoot
    {
        static DiContainer _container;

        static StaticCompositionRoot()
        {
            _container = new DiContainer();
        }

        public static DiContainer Container
        {
            get
            {
                return _container;
            }
        }
    }
}
```

Then changing this line:

```
var container = new DiContainer();
```

To this:

```
var container = new DiContainer(StaticCompositionRoot.Container);
```

Inside `GlobalCompositionRoot.cs`

Then you should be able to add your objects by calling things like `StaticCompositionRoot.Container.BindInstance(myObject)`

If you can confirm whether that works I'll add it to the main repo

**Comment by nehmebilal** [comment]
Perfect, I will try it out and confirm. 

Thanks!

**Comment by nehmebilal** [comment]
Yep that worked perfectly.

There's one more thing I'd like to be able to do. Once the Unity installer has finished binding dependencies, I'd like to resolve some of the dependencies from the XAML context. I tried to call `StaticCompositionRoot.Container.Resolve<IFoo>()` hoping that it will search all child containers as well but it failed. Any ideas?

**Comment by svermeulen** [comment]
Yeah, the parent containers are not aware of their child containers at all.

Can you call into the Unity API?  If so you could call `GameObject.FindObjectOfType<SceneCompositionRoot>().Container`

**Comment by nehmebilal** [comment]
@svermeulen I can and that works perfectly. I was doing something similar with a static class that holds the container but this is cleaner.

Thanks again!
