### ISSUE TITLE
InitializableManager swallowing exception.

### ISSUE THREAD

**Issue by phamhathanh** [ssannandeji/Zenject-2019#123]
Currently the InitializableManager has a base Exception catch block with a generic return message. I think it's better let the exception just bubble up (rethrow or no catching at all). It would make debugging easier.

**Comment by svermeulen** [comment]
Yes I see what you mean.  It doesn't throw away the exception though - it just wraps it with a new exception.  So `e.InnerException` would contain the original exception.  Problem is, when Unity prints out the exception it doesn't care about inner exceptions.  I haven't seen this issue myself since I use a custom error handling system that actually does print that stuff out.

Anyway, you're right, it's not very helpful the way it is so I'll remove
