### ISSUE TITLE
extraArgs for Resolve calls?

### ISSUE THREAD

**Issue by 4xisblack** [ssannandeji/Zenject-2019#125]
I'm attempting to instantiate a prefab, one of whose MonoBehaviours ('DialogOptionController') requires a class called 'DialogOption' whose constructor takes an integer. What I'd like to do is pass the integer into this constructor via IInstantiator's extraArgs feature, e.g.: 

```
var index = 0;
instantiator.InstantiatePrefabResourceForComponent<DialogOptionController>("DialogOptionBlock", new object[] { index });
```

The problem I encounter is that I'm attempting to create DialogOption via a container-level binding, as in:

 `Container.Bind<DialogOption>();`

So while it is injecting DialogOptionController it has the integer available as an extra argument, BUT when it calls Resolve() to acquire a DialogOption this argument does not carry across. I think it might be cool if Resolve could take an extra args list (and if the various IInstantiator methods chained their arguments into Resolve calls).

**Comment by svermeulen** [comment]
Can you do something like the approach described here?
https://github.com/modesttree/Zenject/tree/f0dd30ad451dcbc3eb17e636455a6c89b14ad537#advanced-factory-construction-using-subcontainers

In other words, something like this:

```
int index = 0;

var subContainer = Container.CreateSubContainer();
subContainer.BindInstance(index).WhenInjectedInto<DialogOption>();
return subContainer.InstantiatePrefabResourceForComponent<DialogOptionController>("DialogOptionBlock");
```

**Comment by 4xisblack** [comment]
I have been working on moving my tech over to the subcontainers/facades model the past week or two; it is indeed pretty great!

I ended up creating a DialogOption manually and injecting that as an extra arg, which solved this specific problem. I would claim, however, that since Zenject has robust support for transient bindings in most other cases, it's a little inconsistent for extraArgs to be unavailable for use beyond the first layer of injection scope.

I guess I feel like the extra args thing stands halfway between being a 'bind scope' sorta like the framework used to have and being a small utility for populating the arguments of some particular constructor. I think it works well for C# classes, where it serves as precisely the latter thing; but then when it comes time to instantiate prefabs it gets weird, since extra arguments are available to many different monobehaviours within the GameObject hierarchy but not for the composition hierarchies of C# classes.

**Comment by svermeulen** [comment]
I think I see what you're saying.  The extraArgs passed to InstantiatePrefab can be used by any Monobehaviour's on the prefab, or even multiple Monobehaviour's, as long as all the arguments are injected somewhere (and if they are not all used then it throws exceptions).  Whereas, if you use InstantiatePrefabForComponent, or Instantiate<> for non-Monobehaviour's, the extraArgs's are applied to the specified class only.

I agree that the inconsistency here is kind of weird.  I think that the way Instantiate<> and InstantiatePrefabForComponent<> work are the better ways to handle extraArgs's though.

If you want to have the extra args apply to the entire object graph, either for a prefab or for a non-Monobehaviour, you can just use a subcontainer like I mentioned above.  This eliminates the need to pass down dependencies across multiple layers.

It's actually tempting to just remove extraArgs from InstantiatePrefab to solve the inconsistency, especially since subcontainers can be used to address that use case anyway.

**Comment by 4xisblack** [comment]
Yeah, removing it from InstantiatePrefab sounds reasonable to me as well.

**Comment by svermeulen** [comment]
Fixed in version 5
