### ISSUE TITLE
Having issues to understand NonLazy

### ISSUE THREAD

**Issue by 0x-1** [ssannandeji/Zenject-2019#129]
`Container.Bind<Whatever>().AsSingle().NonLazy();`

Expected: Constructor call for "Whatever"
Actual: Constructor after first injected call
Version: NonUnity

**Comment by svermeulen** [comment]
I was just about to take a look at this issue today.  Did you figure it out and that's why you closed it?

If you're using Zenject outside of unity then you might have to replicate some of the functionality that you find in classes like SceneContext.  That's what does the initial resolve for all components that are marked as NonLazy (by calling Container.ResolveDependencyRoots())

**Comment by 0x-1** [comment]
yeah figured it out myself. Thanks for the reply tho.
Solution was indeed to call Container.ResolveDependencyRoots()
