### ISSUE TITLE
Prefab instantiation arguments must not be null

### ISSUE THREAD

**Issue by arijoon** [ssannandeji/Zenject-2019#146]
Let's say I have object `A` as a prefab which has the following script component (Assume `Settings` has been properly blinded. 

```
public class ChainConnector : MonoBehaviour
    {
        public int ConnectedSource = -1;

        private Settings _settings;

        [Inject]
        public void Init(Settings settings)
        {
            _settings = settings;
        }
}
```

If I try to instantiate object A using

```
 var result =  _container.InstantiatePrefabExplicit(A, null, "As Group name", false);
```

it'll fail. However if I do the following in objects created at startup or by unity it'll work fine. I think this should be added to the docs.  

this will solve the issue

```
 var result =  _container.InstantiatePrefabExplicit(A, new List<TypeValuePair>(), "A Group name", false);
```

**Comment by svermeulen** [comment]
Why are you using `InstantiatePrefabExplicit` as opposed to `InstantiatePrefab`?  Not all that important since this same issue applies to `InstantiatePrefab`, but I'm just curious.

I have added a comment above the InstantiatePrefab methods to clarify that the argument list must be non-null.  When I write code I always assume non-null for lists.  I prefer the default value for lists to be the empty list instead of null.

**Comment by arijoon** [comment]
That is a good assumption. I raised the issue since that version used to work in previous versions of Zenject and took me a little while to exactly figure where it was happening. Zenject is written very well and the code itself is self documenting, that helped me in narrowing it down.

I wrote my own PrefabFactory, and used `InstantiatePrefabExplicit` in a previous version of Zenject and kept the same when I migrated to latest. I don't really remember why I used the explicit method nor what exactly is their difference.
