### ISSUE TITLE
Rebind IInitializable in SceneContext wont work

### ISSUE THREAD

**Issue by FriedrichWessel** [ssannandeji/Zenject-2019#149]
I have the following Installer connected to my ProjectContext: 

``` c#
public class ProjectInstaller : MonoInstaller 
{
    public override void InstallBindings ()
    {
        Container.Bind<IInitializable> ().To<SystemLoader>().AsSingle();
    }
}
```

In my Integration Test scene I would like to override this SystemLoader with a dummy loader. So I created a SceneContext and attached the following Installer: 

``` c#
public class IntegrationTestInstaller : MonoInstaller 
{
    public override void InstallBindings ()
    {
        Container.ParentContainer.Unbind<IInitializable>();
        Container.ParentContainer.Bind<IInitializable>().To<DummySystemLoader>().AsSingle(); 
    }
}
```

But still the Initialize() function from the SystemLoader is called, the DummySystemLoader is never called. 

What is wrong with the code above ? 

Thanks for your help!

Friedrich

**Comment by svermeulen** [comment]
I think the SystemLoader Initialize is still called because the ProjectContext has already injected everything by the time your IntegrationTestInstaller is called.  You can't really customize ParentContainer like that after ParentContainer has already executed the Resolve / Inject phase.

Also, calling `Container.Unbind<IInitializable>` seems pretty dangerous since it will remove all bindings to `IInitializable` and not just the `SystemLoader` one.  Are you sure that's what you want?

What you're running into here is common issue with using ProjectContext - It means that the bindings you add there have to work with every single scene in your Unity project, including test scenes where you might not want them.

I can't think of a way for you to change ProjectContext for a particular scene.  And as I said, you can't use Unbind / Rebind since the container has finished injected by that point.  Though I would probably discourage using Unbind / Rebind anyway since I consider them bad practice.

Maybe the solution is to not have `SystemLoader` in the ProjectContext in the first place

Sorry I don't really have a better recommendation for you

**Comment by FriedrichWessel** [comment]
Thanks for the anwer. I was afraid it is this way. Unfortuntatly this makes the ProjectContext nearly unusable. But I will change everything to the SceneContext and work from there. Thanks

**Comment by svermeulen** [comment]
Yep, using ProjectContext is simple and easy but if you have a big unity project with many different requirements it definitely becomes an issue.   For example, even trying to run the Zenject samples within your own unity project will trigger your ProjectContext which makes no sense.

A better alternative to using ProjectContext might be to have a main scene that uses SceneContext and sets up your common bindings, and then load other scenes "underneath" that scene by using ZenjectSceneLoader and passing along LoadSceneContainerMode.Child

**Comment by FriedrichWessel** [comment]
My current idea looks like this: 
1. Leave the ProjectContext with an empty installer 
2. In the first scene installer bind all Game wide bindings to the ParentContainer

This way I can still use the ProjectContext - but have other bindinds - depend on what scene I start with, 

Is this a good workflow - or is it to hacky ?

**Comment by svermeulen** [comment]
I don't think that will work very well since the ProjectContext will have finished initializing by the time you execute your scene installers, so the bindings you add to the parent container might not be used.  For example, adding an `ITickable` binding that way will not receive calls to its `Tick` method

**Comment by FriedrichWessel** [comment]
Thanks alot for your help!
