### ISSUE TITLE
Loading more than one scene additively with the ZenjectSceneLoader doesn't work

### ISSUE THREAD

**Issue by halzate93** [ssannandeji/Zenject-2019#164]
I ran into a problem recently. I'm trying to create a dynamic content system so I can load and unload different sections of a level without loading screens.

The catch though, seems to be that I need to load more than one scene at a time. And using the ZenjectSceneLoader the second loaded scene doesn't inherit the dependencies installed on the main scene context.

I'm already using the LoadSceneContainerMode.Child

Here's an example of the problem: https://github.com/halzate93/additive-loading-test

Any ideas on what could be going wrong?

**Comment by halzate93** [comment]
I load scenes using the [ZenjectSceneLoader](https://github.com/modesttree/Zenject/blob/23be96f748e083752a5f62d2b308b51c818bb356/UnityProject/Assets/Zenject/Source/Util/ZenjectSceneLoader.cs), I want the additional scenes to keep the installers I configured on the main scene, my current setup is this one:

![setup](https://s14.postimg.org/dpjictd01/Screen_Shot_2016_10_22_at_10_21_52_AM.png)

The idea is that the _Greeters_ all use the _Logger_ created on the test installer. However, the _Greeter_ on _Additional Scene 2_ fails to resolve the _Logger_ created on the _Main Scene_.

![error](https://s14.postimg.org/d3bgxvp9t/Screen_Shot_2016_10_22_at_10_28_48_AM.png)

The code I use to load the scenes is this one:

``` cs
using UnityEngine;
using Zenject;

public class AdditionalSceneLoader : MonoBehaviour 
{
    [SerializeField]
    private string[] additionalScenes;

    [Inject]
    private ZenjectSceneLoader loader;

    private void Awake () 
    {
        foreach (string sceneName in additionalScenes)
        {
            loader.LoadSceneAdditive (sceneName, LoadSceneContainerMode.Child);
        }
    }
}
```

Any help will be appreciated!

**Comment by svermeulen** [comment]
Thanks for the minimal reproducible example  :)

I can see what the issue is.  When you load scenes this way, Unity delays actually starting the scene until the next frame.  And the ZenjectSceneLoader uses a static field to temporarily store the arguments to the new scene.  When you load multiple scenes in sequence like this, this static field gets overridden.

You have two options to fix it:
1. You can either load each scene using `ZenjectSceneLoader.LoadSceneAsync` from within a coroutine.
2. You can use a new undocumented feature called "scene contract names".  The way this works is that you would fill in the "contract name" field on the scene context in your main scene (for eg. you could use "Main") and then you would set the "parent contract name" to this same value on all the scenes you want to parent to it, then you could just load the scene normally without even using ZenjectSceneLoader

Both of these are only available on the develop branch, however it is pretty stable, so you should be fine to use it.  I'm planning on documenting this stuff this weekend and then merging it back into master as version 4.6, so you could also just wait for that.

**Comment by svermeulen** [comment]
The other nice thing about option 2 is that you can use Unity's edit-time multi-scene support.  ie. You could drag all your scenes into the scene heirarchy then hit play, without the need to load them dynamically

**Comment by halzate93** [comment]
Thanks for the quick answer! I'll play around with the contract names, and if I can't figure it out I will go with the coroutine solution. The scene contract names sounds way nicer though.
