### ISSUE TITLE
[Idea] Workaround to allow injection to occur before Awake/Start for dynamically instantiated objects

### ISSUE THREAD

**Issue by magus237** [ssannandeji/Zenject-2019#174]
Hi,

I've been using Zenject for a couple of months, and I really enjoy it.

I've come up with the following workaround to have the inject methods called before Awake/Start on dynamically instantiated objects : just before calling diContainer.InstantiatePrefab, I actually disable the source prefab, and right after that, I re-enable the prefab and the instanciated object. That way, the inject methods are indeed called before Awake/Start.

Do you think that workaround would be reasonable enough to make it into Zenject ?

**Comment by svermeulen** [comment]
I think that's a pretty good idea actually.  It would be nice for people that didn't want to use [Inject] methods everywhere and would prefer to use Start instead.

We used to be doing something similar during validation.  I'm not sure why we never thought to do it for all prefabs.

**Comment by svermeulen** [comment]
One issue with this idea that just occurred to me:  Sometimes people want to instantiate their prefabs as disabled (eg. #184) or partially disabled.  So we can't simply disable the prefab, then instantiate, then re-enable.  So it seems to me that our options are:

1) Just disable and re-enable the whole prefab anyway.  #184 has existed since the original days of Zenject and nobody has complained about the fact that their prefabs are automatically enabled so maybe it's not such an issue
2) Record which transforms are enabled/disabled for every transform on the prefab, then disable the entire prefab, then instantiate, then set each transform on both the prefab and the newly instantiated game object to the right active state.  This would solve both this issue and #184 but there could be performance costs here if you're using a prefab with say 20k transforms.
3) Just leave it as it is and live with the fact that dynamically instantiated prefabs cannot access injected dependencies in their awake method.  This might not be such a big deal since really, you can always just use an [Inject] method instead of an awake method.

I think either 1 or 3 are probably the best options.

**Comment by magus237** [comment]
Hi,

Actually, I'm doing something like this in my code :
```
void TweakedInstantiate(GameObject prefab) {
	bool active = prefab.activeSelf;
	if (active) prefab.SetActive(false);
	GameObject go = GameObject.Instantiate(prefab);
	if (active) {
		go.SetActive(true);
		prefab.SetActive(true);
	}
}
```

That way, disabled prefabs are instantiated as disabled gameobjects, and enabled prefabs as enabled gameobjects. This also works for compound prefabs with the root enabled and some children disabled, ie. disabled children remain disabled in the instantiated gameobject.

I tested various scenarios (on Unity 5.4.2) without noticing anything unexpected or that contradicts the docs ([https://docs.unity3d.com/Manual/DeactivatingGameObjects.html](https://docs.unity3d.com/Manual/DeactivatingGameObjects.html)).

Of course, I'm no Unity expert, so I may not see all the implications...

**Comment by svermeulen** [comment]
Oh ok, I see what you mean.  For some reason, I thought that SetActive was recursive and therefore you would lose the active state in child transforms.  Your solution actually does seem like it will work.

**Comment by svermeulen** [comment]
One issue with this approach that occurred to me today is that the prefab will be disabled when its [Inject] methods are called.   So if anyone has code inside [Inject] methods that rely on the game object being enabled, then this change will break that code.  Though you might argue that in that case they might as well use Start / Awake / OnEnable instead.

Something else worth mentioning is that it seems that at least with newer versions of unity, that the Start() method is actually not called immediately on instantiate.  Unity seems to wait until the end of the frame to call it for some reason.  Not sure if this is new behaviour or it's always been this way, but worth mentioning.

I still think this change is worth doing - just calling out a few implications of it

**Comment by magus237** [comment]
I agree that it might be an issue if someone relies on the active state of the object in an [Inject] method, but I believe it is a small price to pay to allow the [Inject]/Awake/Start methods to always be called in the same order, regardless of whether the object is dynamically instantiated or not.

For the story, I had some collectible objects that used [Inject], Awake and Start for their initialization logic. These objects were only instantiated at design time, so it worked fine, until I decided that some of them could be spawned. And then of course I got null references because the dependencies were used in Awake and Start and the [Inject] method had not been called. So I had to move all my initialization logic into the [Inject] method, but I felt very bad doing this, as I like to keep my [Inject] methods "pure" (that means, dedicated to dependency injection only).

I see that you've made the change to Zenject, so, a big thanks for this improvement !
I definately have to buy you some coffee ;)

**Comment by svermeulen** [comment]
Exactly yeah, the trade off definitely seems worth it.  I'm the same as you in that I don't like using [Inject] for initialization.  This is why my convention is to call the method Construct - to mimic the behaviour of constructors.  But without this change we are kind of forced into using [Inject] for initialization logic, since the alternatives all have their own issues.  And like you say - if you're already using Start() or Awake() then you have to change to use [Inject] when you create objects dynamically, which can be pretty annoying

So this change seems like a nice win.  Thanks for the suggestion  :)

**Comment by Sixze** [comment]
Good work, but it looks like you forgot to change the old behavior when creating an instance of the ProjectContext prefab :)

**Comment by svermeulen** [comment]
@SteamSector You're right

@magus237 Thanks for the coffee this morning  :)

**Comment by Sixze** [comment]
Also (this is most likely not related to the topic, but still), I think it would be great to be able to instantiate a prefab as completely disabled:
```csharp
FromComponentInNewPrefab(UnityEngine.Object prefab, createDisabled bool = false)
```

For example, when I use MemoryPool for some objects, firstly, I disable them, then change these settings as desired, and only after, when they are spawning, activate them, but when instances of these objects are first created, they are created activated (which leads to errors because many parameters are not set) and only then if you use MonoMemoryPool they become disabled. And to solve this problem you have to do something like this:
```csharp
_lobbyMemberPrefab.gameObject.SetActive(false);

Container.BindMemoryPool<LobbyMemberControl, LobbyMemberControl.Pool>()
    .WithInitialSize(_lobbyMemberPoolInitialSize)
    .FromComponentInNewPrefab(_lobbyMemberPrefab)
    .UnderTransformGroup("Lobby Member Controls Pool");
```
But in my opinion such approach can potentially lead to errors (you have to remember in advance to disable prefabs via code or editor), it also brings inconvenience if you use the prefab on the scene, or when you edit it because its disabled state is stored permanently after you change it in play mode.

What do you think about this ?

**Comment by svermeulen** [comment]
Fixed project context to follow the same strategy so that injection always occur before awake.  

@SteamSector I also moved your suggestion for a parameter to issue #258
