### ISSUE TITLE
Assert hit! Found 1 methods still added to signal if stopping with play button

### ISSUE THREAD

**Issue by firegate666** [ssannandeji/Zenject-2019#178]
I am using Zenject and signal and set up my signals in intialize and remove them OnDestroy.
If I play the game normally and let my code handle the destroying, everything is fine.

But if I stop the game using the play button while in the game, I get the following assertion. Debugging shows that Zenject is destroyed at first, then the rest. Using Zenject 4.7

`ZenjectException: Assert hit! Found 1 methods still added to signal 'SignalChangeWeapon'.  Methods: Player.changeWeapon
ModestTree.Assert.Throw (System.String message) (at Assets/Scripts/External/Zenject/Source/Internal/Assert.cs:245)
ModestTree.Assert.That (Boolean condition, System.Func`1 messageGenerator) (at Assets/Scripts/External/Zenject/Source/Internal/Assert.cs:223)
Zenject.Signal`2[SignalChangeWeapon,System.Int32].System.IDisposable.Dispose () (at Assets/Scripts/External/Zenject/OptionalExtras/CommandsAndSignals/Signal/Signal1.cs:50)
Zenject.DisposableManager.Dispose () (at Assets/Scripts/External/Zenject/Source/Runtime/DisposableManager.cs:69)
Rethrow as ZenjectException: Error occurred while disposing IDisposable with type 'SignalChangeWeapon'
Zenject.DisposableManager.Dispose () (at Assets/Scripts/External/Zenject/Source/Runtime/DisposableManager.cs:73)
Zenject.MonoKernel.OnApplicationQuit () (at Assets/Scripts/External/Zenject/Source/Runtime/Kernels/MonoKernel.cs:71)`

**Comment by svermeulen** [comment]
Yes, sorry - that is an overly aggressive assert that should be removed.  It's not an issue for our team because we always make sure zenject is destroyed last (which you can do by parenting everything underneath SceneContext).  But for most people this isn't the case.

I've removed it in the git repo so this issue will disappear with the next release (which I plan to make today).  If you need the fix immediately, you can either update zenject from the git repo directly or just remove the assert directly from your copy of zenject.

**Comment by firegate666** [comment]
Thank you, no need to hurry since on normal exit we do not have the issue.

**Comment by colinmacleod** [comment]
Hey, Steve, 

I'm experiencing this issue too, on objects that are dynamically created. I clean up the signal in OnDestroy().
I have "Parent New Objects Under Root" set true on the SceneContext. I can see from log output the assertion kicks in and my objects are destroyed after.

Any ideas?

**Comment by svermeulen** [comment]
Oh yeah, that makes sense actually.  If everything is under SceneContext, then all the disposables are called before the the game objects get their OnDestroy called, so the signals do their dispose checks before you have removed your listeners in ondestroy

I would suggest just commenting out the dispose logic in the signal classes for now.  I'm going to remove those dispose checks in the repo too, since there isn't really a reliable way to really check that

**Comment by colinmacleod** [comment]
Sure - that's fine. It's a really nice to check, so it's a shame to remove that - would I be better making them disposables rather than using OnDestroy? (They are all monobehaviours but they are dynamically created via a Factory.)

**Comment by svermeulen** [comment]
You could make them IDisposable's but that wouldn't help because they are dynamic.  For IDisposable.Dispose to be called it needs to be added to the initial object graph.  Unless you explicitly add it to the DisposableManager.

It would be nice to check, but I don't think there is a way to ensure that the check occurs after absolutely everything.  The "Script Execution Order" that unity provides does not apply to the OnDestroy events.  The only way to have any control over destruction order is to use transform parenting, since root-level transforms are destroyed first.  This is why I like to use the optional flag on scene context to parent everything underneath it - since that way, I can guarantee to have my IDisposables called before all the game objects in the scene are destroyed in some unpredictable order.  But I don't know of a way to execute code after that.
