### ISSUE TITLE
GameDecoratorInstaller in Asteroids demo not working out of the box

### ISSUE THREAD

**Issue by tomsseisums** [ssannandeji/Zenject-2019#180]
While going through the Asteroids demo in order to understand stuff and reading documentation in background, I thought that I could implement a [Scene Decorator](https://github.com/modesttree/Zenject#scenes-decorator), given the fact that [`GameDecoratorInstaller`](https://github.com/modesttree/Zenject/blob/master/UnityProject/Assets/Zenject/OptionalExtras/SampleGame1%20(Beginner)/Scripts/Installers/GameDecoratorInstaller.cs) is already provided. I didn't find a Scene for it, though.

Anyways... I followed the instructions and set everything up, though, the `ShipStateMoving.Settings` were not overriden. To see if the Decorator is actually called, I set up some `Log.Info` entries, and yes, they are called.

I [checked out some older revisions for the file](https://github.com/modesttree/Zenject/blob/v4.5/UnityProject/Assets/Zenject/OptionalExtras/SampleGame1%20(Beginner)/Scripts/Installers/GameDecoratorInstaller.cs) and found out that previously it had implemented a `DecoratorInstaller` which isn't available anymore.

Okay, I was thinking that maybe there is some magic happening behind the scenes, so a simple `BindInstance` would work - nope:

    ZenjectException: Assert hit! Found multiple matches when only one was expected for type 'AsteroidManager.Settings' while building object with type 'AsteroidManager'. 

Okay, looks like Rebind might do it. Though, I already had the suspicion that it shouldn't be working because `GameDecoratorInstaller` is Installed before `GameInstaller`. And yes, it didn't work.

Seeing that the value for `AsteroidManager._autoSpawn` is injected by `WhenInjectedInto<T>()` I went on to give that a shot, and finally, it's working!

Though... I am not sure if this is the preferred way.. Could the documentation be expanded for overrides with Scene Decorators?

**Comment by svermeulen** [comment]
Hi Tom,
That file (GameDecoratorInstaller.cs) was accidentally left in the repository.  That should have been deleted when SceneDecoratorContext changed.

The way decorators used to work is that they provided a way to install bindings after the main scene had finished installing all its bindings.  This allowed things like calling Rebind or Unbind, and then binding those types to something new.  However, this was removed due to the fact that very few people used that, it wasn't that useful, it was a maintenance headache, and was also kind of bad practice to begin with.

If you want to do something similar now, I'd recommend one of the following methods:

1.  Install the new value in GameDecoratorInstaller and then add an if statement inside GameSettingsInstaller.  You can't install both because Zenject will not know which one to use
```
    if (!Container.HasBinding<ShipStateMoving.Settings>())
    {
        Container.BindInstance(Ship.StateMoving);
    }
```
2.  Inject any override values into the other installer.  So GameDecoratorInstaller would look like:
```
    [InjectOptional]
    ShipStateMoving.Settings _overrideMoveSettings;

    public override void InstallBindings()
    {
        Container.BindInstance(_overrideMoveSettings ?? Ship.StateMoving);
    }
```

**Comment by tomsseisums** [comment]
Oh, I see.

I actually didn't think of any use case I'd need it, was just going through example files and documentation and saw that the feature is written on, but found no example - thought that it's a homework, ha.

I'll admit that the file looked somewhat suspicious... 

Good stuff to know, thanks!
