### ISSUE TITLE
How to use Zenject interfaces with transient objects?

### ISSUE THREAD

**Issue by mentapro** [ssannandeji/Zenject-2019#193]
I need bind some class as transient but it implements some interfaces like IDisposable (and other zenject interfaces)
How should I properly bind this transient class to make interfaces work correctly with each object?

P.S. I read all Zenject documentation but I didn't find the answer.

**Comment by svermeulen** [comment]
Sounds like you might want to use AsCached.  Does that solve the problem?

**Comment by mentapro** [comment]
No, unfortunately it did not help. Or am I wrong doing something.
My situation: I have factory that creates MonoBehaviour objects (facade). And in Construct method of this object I inject model of created facade. So I bound model as transient, because I need new model for every MonoBehaviour. But my model implements IDisposable interface and there are problems when I write something like: `Container.BindAllInterfacesAndSelf<Model>().AsTransient();`. I get an exception "ZenjectException: Assert hit! Expected type 'System.IDisposable' to be non-abstract".

The other way is when I separately write
`Container.Bind<Model>().AsTransient();`
and
`Container.Bind<IDisposable>().To<Model>().AsTransient();`.
In this case Zenject creates new instance of model when I bind IDisposable. And I have NullReferenceException when Dispose is called.

**Comment by svermeulen** [comment]
So it sounds like what you want to happen is to have a new instance of Model injected into every MonoBehaviour, and also have that Model Disposed() of automatically.  This isn't really possible.  All the objects that are bound to IDisposable must be part of the initial object graph.  This is because the DisposableManager needs to get a List<IDisposable> immediately on startup.

So your options are to either Dispose() of each Model manually, add them to the DisposableManager explicitly, or change your architecture around to not use transient.

**Comment by mentapro** [comment]
Ok, I understand. Thanks for the help! I will call Dispose() from MonoBehaviour's OnDestroy().

P.S. Do you think that architecture with transient - is bad? I just don't want to have installer on every object (like in your sample game 2) because it means that every object will have its own dependencies what I don't need.
