### ISSUE TITLE
Method `FromNewComponentOnNewGameObject` lacks parameter for `GameObjectCreationParameters` in `FactoryFromBinderBase` compared to counterpart found in `FromBinder`

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#209]
When implementing a binding for a factory, I was confused for a moment when the method `FromNewComponentOnNewGameObject` did not let me pass in a `GameObjectCreationParameters` like the non factory binding let me pass in moments before. Is this intentional?

**Comment by Soren025** [comment]
![Image of code](http://puu.sh/u7NIc/d7bae7aa59.png)

**Comment by svermeulen** [comment]
Actually, the bind method that takes GameObjectCreationParameters is a mistake, not the other way around.  The contents of GameObjectCreationParameters should be set using the fluent interface instead of passing that data directly.  For example:

```
            Container.Bind<Foo>().FromNewComponentOnNewGameObject()
                .WithGameObjectName("foo").UnderTransformGroup("Foos");
```

I'll make the version that takes GameObjectCreationParameters private

**Comment by Soren025** [comment]
I see, thanks.
