### ISSUE TITLE
Zenject creates more instances than is necessary + IDispose.Dispose() not called.

### ISSUE THREAD

**Issue by korober** [ssannandeji/Zenject-2019#211]
How to reproduce: 
1. Open project, load scene Assets\Scenes\Main.unity
2. Hit Play button, see console output.

Description:
Scene contains 3 View that should be initialized by new Controller instance every time. 
1. Problem: Further instance:
Expected: zenject creates 3 controllers for 3 views (one controller per each view)
Actual: zenject creates 4 (3+1) controllers 

2. Problem: Dispose() strange behaviour:
Expected: zenject calls Controller.Dispose() for each created controller (id = 1,2,3)
Actual: zenject calls Controller.Dispose just for further controler (id = 4)

Please, correct me, if it's my mistake with binding.
Unity project:
[Zenject_issue.zip](https://github.com/modesttree/Zenject/files/785921/Zenject_issue.zip)
Screenshot:
![zenject_issue](https://cloud.githubusercontent.com/assets/12730722/23103504/931bfb50-f6ee-11e6-9ceb-5f00280d50c8.png)

**Comment by svermeulen** [comment]
The issue here is this line:

```
Container.BindInterfacesTo<Controller>().AsTransient()
```

This gets expanded to:

```
Container.Bind<IController>().To<Controller>().AsTransient();
Container.Bind<IDisposable>().To<Controller>().AsTransient();
```

Which means that zenject will create a unique instance for each interface.  When using BindInterfacesTo, you always want to use either AsCached or AsSingle:

```
Container.BindInterfacesTo<Controller>().AsCached()
```

**Comment by korober** [comment]
Hi, svermeulen, and thank you for the Zenject! It's amazing!

So, there is no way to ask Zenject to register every created (by Zenject) controller (binded AsTransient) as IDisposable?
If I should use:
`Container.Bind<IController>().To<Controller>().AsTransient();
`
How to ask Zenject to call Dispose for each created instance of controller?
My project is not good sample, just want to understand does Zenject have this ability or not.

**Comment by svermeulen** [comment]
That's correct - there's no way to get zenject to automatically dispose of objects marked AsTransient which are also IDisposable.  This is because Zenject will only dispose of IDisposable's that are bound to IDisposable and are part of the initial object graph.  This is because the DisposableManager needs to get a `List<IDisposable>` immediately on startup.

This is true for the other interfaces (IInitializable, ITickable, IDisposable) as well. When dealing with dynamically created objects that you want to implement these interfaces it's often best to handle these yourself.  Usually what I end up doing is creating a higher level manager class to do this.

**Comment by korober** [comment]
Thank you for your time!
