### ISSUE TITLE
Testability implications in 5.0

### ISSUE THREAD

**Issue by steinjak** [ssannandeji/Zenject-2019#212]
Hi,

Thanks for making and maintaining Zenject - a DI container is essential to manage a loosely coupled and testable design! Upgrading to 5.0 in one of our projects, we've come across an issue related to unit tests and the ability to do TDD.

Up until 5.0, signals have been testable outside of the editor, which is very useful for running tests in the IDE as part of doing TDD for code that is Unity-independent.

However, two changes in 5.0 make this more challenging (see below for a code example):
1. Signals now depend on having an instance of `SignalManager` injected, which is done through a private method. We could work around this one by using the container to instantiate signals in test, if it wasn't for the next change.
2. Zenject now conditionally compiles profiler hook code based on the define `UNITY_EDITOR` rather than `PROFILING_ENABLED` (for example in `InstantiateExplicit` or `Signal.Fire`), resulting in `MissingMethodException` if any test involving Zenject is run outside of the context of the editor. This is harder to work around; possibly we can change the generated `.csproj`-file on generation, taking out the define of `UNITY_EDITOR`.

Before, signals could be tested like this (runnable both inside and outside of the editor):
```csharp
var signalWasFired = false;

var signal = new TestSignal();
signal.Listen(() => signalWasFired = true);
signal.Fire();

Assert.That(signalWasFired, Is.EqualTo(true));
```

Now, we need to do (and we are forced to switch to the editor to make the test run):
```csharp
var signalWasFired = false;

Container.Bind<SignalManager>().AsSingle();
Container.DeclareSignal<TestSignal>();

var signal = Container.Resolve<TestSignal>();
signal.Listen(() => signalWasFired = true);
signal.Fire();

Assert.That(signalWasFired, Is.EqualTo(true));
```

I can see that there is a good reason for these changes, but maybe there is a way to avoid the `MissingMethodException` when running tests outside of the editor? For instance by doing something (involving `AppDomain.Current`?) in `ProfileBlock.Start` to find out whether or not calling `Profiler.enabled` is safe?

**Comment by svermeulen** [comment]
Yes I know what you mean.  I like to run unit tests outside of Unity as well directly in whatever text editor I'm using.

The reason that it automatically uses ProfileBlock is so that that profiling information is displayed in the Unity profiler for ITickables, IInitializable's, Signals, etc. just like it is for any MonoBehaviour-derived methods.

What we do in our code base to allow tests outside unity is that we add another define for this.  So for us, the beginning of ProfileBlock looks like this:

```
    public class ProfileBlock : IDisposable
    {
#if UNITY_EDITOR && !ZEN_TESTS_OUTSIDE_UNITY
        static bool _isActive;

        bool _rootBlock;
```

I didn't commit that though because I wasn't sure if anyone else really cared about that.

I actually like your idea of doing a runtime check better though.

I just committed a change that uses AppDomain.Current like you suggest, so give that a try.  Not sure if it's the best way of determining whether Unity assemblies can be accessed but seems to work well in my tests.

**Comment by steinjak** [comment]
Thanks for getting back to me so quickly! I bought you a coffee ($2.56) ;-)

I've been wondering how people solve this problem, so it was interesting to see your solution; I agree that checking AppDomain.Current smells, I just haven't found or seen any good solutions (yet) on how to determine which context the code is running in without touching the functions in Unity itself (which, of course, throw exceptions outside of Unity...).

I'll close this issue and try out your latest change. Again, thanks! Quick and detailed responses also gives faith in having made the right choice of container library.
