### ISSUE TITLE
Injecting newly created gameobject?

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#230]
I'm trying to inject a transform of a newly created gameobject, but this fails with `ZenjectException: assert hit`.

My installer code is:
`Container.Bind<Transform>().FromNewComponentOnNewGameObject().AsSingle();`

**Comment by svermeulen** [comment]
This was failing because apparently you cannot call `AddComponent<Transform>` since all game objects already have a transform component attached to it.  Since there is no `FromComponentOnNewGameObject` method and we wouldn't want one anyway (since it is really only transform that this is needed for) I changed the `FromNewComponentOnNewGameObject` binding to treat Transform as a special case.  So if you update, that assert should go away now.  Thanks for the report
