### ISSUE TITLE
Signals: Possibility to unbind Signal Handler

### ISSUE THREAD

**Issue by fknr** [ssannandeji/Zenject-2019#233]
It would be convenient to be able to unregister all or specific signal handler.

**Comment by svermeulen** [comment]
If you need to unregister based on some condition at runtime, can't you just use the `+=` method of adding/removing yourself to a signal?  Instead of BindSignal?

It might also be worth mentioning that the signal handler will be automatically unregistered during the IDisposable.Dispose event for the container that you use with BindSignal

**Comment by fknr** [comment]
Since the command class was removed I switched to signal handlers. I am not listening to the signals with += in a service class. 
My use case for un/rebinding handlers on runtime was when I implemented a tutorial system that changed the default behavior of the application when active. I wanted to avoid that the application has to care to much about the tutorial active with conditions and instead remap this:
Container.BindSignal<SometingHappendSignal>().To<DoDefaultActionCommand>(x => x.Execute).AsSingle();
to this when the tutorial is activated and switch back when it ended.
Container.BindSignal<SometingHappendSignal>().To<DoTutorialActionCommand>(x => x.Execute).AsSingle();
