### ISSUE TITLE
Factory same type param injection details?

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#234]
I was curious about the exact details on the order things get injected when dealing with the default factory and parameters. More specifically, if I have two parameters of the same type on the factory, can I predict how they get injected?

A few tests show that it seems to consistently inject the parameters in the order the fields are declared or the order the constructor param are declared, but am unsure if this is guaranteed. I couldn't find any info on the factory documentation on the subject and don't want to make assumptions on implementation details.

**Comment by Soren025** [comment]
I'll post a code example

```csharp
public sealed class Connection
{
    private readonly Cell from;
    private readonly Cell to;

    [Inject]
    private Connection(Cell from, Cell to)
    {
        this.from = from;
        this.to = to;
    }

    public Cell From { get { return from; } }

    public Cell To { get { return to; } }

    public sealed class Factory : Factory<Cell, Cell, Connection>
    {
        // I override the method with `new` to redefine the param names
        public new Connection Create(Cell from, Cell to)
        {
            return base.Create(from, to);
        }
    }
}
```

In this example, I have two parameters of the same type in the factory. As mentioned above, I want to clarity the expected behavior as I could not find this case documented.

**Comment by svermeulen** [comment]
Ok I added a note about the behaviour when it comes to the parameter order to the docs.

This is what I added:

You can have multiple parameters declared with the same type.  In this case, the order that the values are given to the factory will match the parameter order - assuming that you are using constructor or method injection.  However, if you are using field or property injection, then the order that values are injected is not guaranteed to follow the declaration order, since these fields are retrieved using Type.GetFields which does not guarantee order as described <a href="https://msdn.microsoft.com/en-us/library/ch9714z3.aspx">here</a>

**Comment by Soren025** [comment]
ok, cool.
