### ISSUE TITLE
MemoryPooling requires hash-able objects?

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#241]
I was getting into messing with memory pools and noticed became curious about a method `DespawnAll()`, so I peeked in to see what it did. What I found was a `HasSet<TContract>` to hold active items and checks to ensure add and removal took place.

Does this mean that objects can only be pooled if they implement `GetHashCode()`? If so, this decision seems odd to me, ~~and actually breaks what I was planning on using the pooling for~~ (Well, not break. More force me to add an arbitrary incremental `int` to a base class to act as a hash. I suppose this is the intended solution. But I am still curious about the decision).

**Comment by Soren025** [comment]
Silly reason to make an issue for something that wasn't really a problem. Was just curious was all.

**Comment by Soren025** [comment]
oh?

**Comment by svermeulen** [comment]
I think you're right, we shouldn't use HashSet.  I think we should maybe just remove support for DespawnAll entirely to avoid needing to store the active set.

**Comment by svermeulen** [comment]
Related:  https://groups.google.com/forum/#!topic/zenject/iu1Iw1-Umeo

**Comment by svermeulen** [comment]
Fixed by removing HashSet entirely

**Comment by Woody4618** [comment]
Hmm, but how am i now supposed to despawn all?

**Comment by svermeulen** [comment]
You can't and that's intentional.  We want to be able to spawn items from a memory pool and then decide whether or not to return it to the pool.  If we don't return it to the pool, we want to be able to just stop referencing it and then let the garbage collector get rid of it (assuming it's a non monobehaviour).  If we added this feature to despawn all automatically then we couldn't also support making returning to the pool optional, and the latter seems like the better feature to support
