### ISSUE TITLE
[WP8] TypeAnalyzer.GetInjectConstructor strange behavior

### ISSUE THREAD

**Issue by Aszan** [ssannandeji/Zenject-2019#26]
GetInjectConstructor retrieves at least 2 constructors whatever the type:
1. `Void .ctor()` with `Attributes = FamANDAssem | Family | HideBySig | SpecialName | RTSpecialName`
2. `Void .ctor(UIntPtr)` with `Attributes = Private | Family | HideBySig | SpecialName | RTSpecialName`

As none is marked with `[Inject]` `GetInjectConstructor` always returns NULL
If we bypass test

``` C#
if (constructors.HasMoreThan(1))
{
  // This will return null if there is more than one constructor and none are marked with the [Inject] attribute
  return (from c in constructors where c.HasAttribute<InjectAttribute>() select c).SingleOrDefault();
}
```

everything works fine as first one is used as expected.
 Anyone an idea regarding this?

**Comment by svermeulen** [comment]
Currently Zenject is not intelligent enough to choose the constructor for you, so it requires that explicitly mark which constructor you want with the [Inject] attribute.   This means that if you have more than one constructor, Zenject will throw exceptions until you add that attribute.  The example you give works only because it is lucky enough to choose the constructor you wanted.  But what if you wanted to actually inject a UIntPtr into it and therefore wanted it to use the second constructor?

Any reason you can't just use the [Inject] attribute on the constructor you want Zenject to use to solve this problem?

It sounds like it isn't being very helpful reporting this error though so I'll leave this item open until we address that.

**Comment by Aszan** [comment]
I understood that Zenject can not choose for us.
The issue here is that none of my classes has constructor.
Thus I believed that Zenject will only find the default one automatically generated by the compiler.
It works well for windows and android. But when I run it on a windows phone for a reason I cannot explain Zenject find 2 constructors instead one. That's why I report issue.

**Comment by svermeulen** [comment]
I tried to reproduce this in unity editor using platform WP8 but things still seemed to work.  Can you provide a bit of code to show the problem?

**Comment by Aszan** [comment]
Things work well inside Unity Editor for me too but when I open WP8 generated solution and launch it from VS 2013 or deploy on a real WP I got the issue.
I tried my own code and asteroids scene and both failed.
Have you tried this?

**Comment by Odonno** [comment]
Yep, I have the same error... and I have no more than 1 constructor in a class..
I tried by adding Zenject's [Inject] attribute into my constructors but it does not change anything.

That's because in my VS debugger, I can see the 'ContructorInjectables' property of ZenjectTypeInfo's object is equal to 0 when the exception is thrown.
It is inside the "object InstantiateInternal(Type concreteType, IEnumerable<TypeValuePair> extraArgMapParam)" method of "Instantiator" class.
Is that error can be removed by adding a condition in your test ? (like "&& typeInfo.ContructorInjectables.Count > 1").

EDIT : Well, so I tried to fix this with the Count condition but it does not work.
Zenject absolutely try to inject into constructor but there is not. I think that could come from methods above.

**Comment by Odonno** [comment]
Well, so I tried to fix this with the Count condition but it does not work.
Zenject absolutely try to inject into constructor but there is not. I think that could come from methods above.

**Comment by svermeulen** [comment]
I wish I could help with this but I would need to reproduce the problem first and I don't have a WP to test on  :(

If one of you guys figures out a solution let us know.

**Comment by Odonno** [comment]
Did you test with a WP emulator (not the platform editor but an internal emulator device, from Visual Studio) ?

I did not try but I think it will have the same behaviour. You just need a Windows 8 with Visual Studio and Hyper-V (included in Visual Studio installation). Well, you need VT-x virtualization technology enabled in your PC.

**Comment by THplusplus** [comment]
Unity will give EVERY type an additional constructor like

```
internal Classname(UIntPtr dummy) { ... }
```

when building a project for WP8.
I worked around the issue by modifying `TypeAnalyzer.GetInjectContructor(Type)` (see below).
The modification will make Zenject ignore any constructors that match the given signature. You can still have constructors that take one UIntPtr parameter, as long as the parameter is not called "dummy". I know it's not really clean, but if you have to choose between that solution and no solution, use that.

```
        static ConstructorInfo GetInjectConstructor(Type parentType)
        {
            var constructors = parentType.GetConstructors(
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

            constructors = constructors.Where(c => IsValidConstructor(c)).ToArray();

            if (constructors.IsEmpty())
            {
                return null;
            }

            if (constructors.HasMoreThan(1))
            {
                // This will return null if there is more than one constructor and none are marked with the [Inject] attribute
                return (from c in constructors where c.HasAttribute<InjectAttribute>() select c).SingleOrDefault();
            }

            return constructors[0];
        }

        private static bool IsValidConstructor(ConstructorInfo c)
        {
            ParameterInfo[] parms = c.GetParameters();

            // Don't allow WP8 dummy constructors (internal Classname(UIntPtr dummy))
            if (parms.Length == 1)
            {
                if (parms[0].ParameterType == typeof(UIntPtr) && parms[0].Name == "dummy")
                    return false;
            }

            return true;
        }
```

**Comment by Aszan** [comment]
I was not aware about the Unity extra constructor. A **tips & tricks** day is definitively a good one, thank you.
Keeping this in mind I think the modification makes sense and it does not impact code more than necessary. I have to reactivate my Unity stack (long time no use...) to test it but I think this should be integrated in an incoming release. Do you agree Steve?

**Comment by svermeulen** [comment]
Yep that sounds good.  Thanks @THplusplus for reporting this workaround.

I just submitted a slightly modified version of your code (all I did was add a check for WP8).  @Aszan, if you or someone else is able to update and confirm that would be very helpful, since I don't have WP8 to test on.  I'll leave this issue open until someone can confirm
