### ISSUE TITLE
Inject multiple subclasses into "params"

### ISSUE THREAD

**Issue by evancorl** [ssannandeji/Zenject-2019#279]
I have a situation similar to the case below:

```
public class Animal {

}

public class Monkey : Animal {
  
}

public class Lion : Animal {

}
```

```
public class Zoo {

  public readonly Animals;

  [Inject]
  public Zoo(params Animal[] animals) {
    Animals = animals;
  }
}
```

Is it possible to inject a list of params with multiple subclasses (or the same class, for that matter)?

i.e., something like this:

```
Container.Bind<Animal[]>().To<Monkey, Lion>().WhenInjectedInto<Zoo>();
```

Thanks in advance. This framework has been great to work with.

**Comment by svermeulen** [comment]
I think this should do what you want:

```
Container.Bind<Animal>().To<Monkey>().WhenInjectedInto<Zoo>();
Container.Bind<Animal>().To<Lion>().WhenInjectedInto<Zoo>();
```

Or if you want to make it one line you can do that too like this:

```
Container.Bind<Animal>().To(typeof(Monkey), typeof(Lion)).WhenInjectedInto<Zoo>();
```

You'll also need to change your constructor to take a list instead of a params array like the following code.  (When multiple bindings for the same contract type are found the result is a list).

```
using System.Linq;

public class Zoo {

  public readonly Animals;

  [Inject]
  public Zoo(List<Animal> animals) {
    Animals = animals.ToArray();
  }
}
```

Note that you probably will need to add AsSingle, AsTransient or AsCached to that.

**Comment by evancorl** [comment]
@svermeulen That worked perfectly. I must have missed the [List Bindings](https://github.com/modesttree/Zenject#list-bindings) section in the documentation because I was searching for `params`. Thanks for the quick response!
