### ISSUE TITLE
REQUEST: Provide Unity Zenject in DLL form

### ISSUE THREAD

**Issue by RichyHBM** [ssannandeji/Zenject-2019#291]
Currently you have to import the unity package which adds a lot of CS files to a project, it would be much more convenient if you could add a couple of DLL's (zenject, zenject editor, plugins...)

**Comment by simeonradivoev** [comment]
unfortunately you can't have a DLL with the built in unity defines like UNITY_EDITOR or UNITY_5_6_OR_NEWER. The only way to do it is by having a 3 DLLs.

1. DLL for the unity editor specific
2. DLL for runtime with UNITY_EDITOR defined
3. DLL for runtime without UNITY_EDITOR defined

You can manually set in the editor which dll is used for the editor or just build. Unfortunately the editor shows 2 versions of the components in some cases.

**Comment by svermeulen** [comment]
Exactly, yeah.  It's even worse than that too, because Zenject uses other defines too like UNITY_WSA and ENABLE_DOTNET, so we'd need dlls for those too.  In some cases you can change these to be a runtime check, but in many cases you can't.  And even if you did create all these separate dlls my guess would be that you'd still run into issues with component references getting lost when switching platforms.

**Comment by Soren025** [comment]
@svermeulen This issue may become relevant with the new feature in the latest unity beta. Not relevant in terms of providing a DLL, rather relevant in that the feature does the same thing as providing a DLL.
https://drive.google.com/file/d/0Bykxs2qcd6PSUTJhYkJySS1hazA/view
