### ISSUE TITLE
Tickable priority binding missing?

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#292]
The documented means of binding `ITickable` priority seems to be missing from `DIContainer`. As far as I can tell, I couldn't find any different way to do so.

**Comment by svermeulen** [comment]
You mean this?

```Container.BindTickableExecutionOrder<Foo>(10);```

This seems to work when I try it

**Comment by Soren025** [comment]
That method does not show up for me in intellisense, nor does it show up in the `DIContainer` class, or any method with the word "Order" in its name. The version I have is `5.2.0`.

**Comment by svermeulen** [comment]
Oh I bet it's because those methods are extension methods, which means you have to execute "using Zenject" at the top of your file to see them.  I'm guessing you refer to zenject classes using their namespace (eg. `Zenject.MonoInstaller`)?

I think we should make these normal methods to avoid this problem

**Comment by Soren025** [comment]
Ah, not having the namespace was indeed the issue, tho not for the reason you theorized. I was trying to bind in a class that extends a class that extends `MonoInstaller`

example...
```csharp
using Zenject;

public class BaseInstallerClass : MonoInstaller
{

}
----------------------- Separate File ------------------
public class SubInstallerClass : BaseInstallerClass
{
    public override InstallBindings()
    {
        // The priority binding methods do not show up
    }
}
```
