### ISSUE TITLE
Does Zenject no longer support multithreading?

### ISSUE THREAD

**Issue by ganaware** [ssannandeji/Zenject-2019#296]
There is a define constant: ZEN_MULTITHREADING .

It had been documented until b2ffa3bf5fce63d2a3eb5c527b00cbc6f1bcaa13, and defined in csprojs unitl b2ffa3bf5fce63d2a3eb5c527b00cbc6f1bcaa13.

But now, none of them mentions ZEN_MULTITHREADING.

Does Zenject no longer support multithreading?

**Comment by svermeulen** [comment]
No - it is still supported.  In fact, we use Zenject at our company for an ASP.NET MVC project that involves many threads at once, so we need it.  It is off by default though - you need to define `ZEN_MULTITHREADING` yourself.

The reason it is off by default is because right now, the way Zenject checks for circular dependencies requires one thread.  We have ideas of fixing that in the future (by looking at InjectContext chains instead of storing current lookups in member variables) but for now that's how it is

**Comment by ganaware** [comment]
I'm relieved to hear that.
I'll define ZEN_MULTITHREADING by myself.
Thank you!
