### ISSUE TITLE
Unable to Bind ZenjectSceneLoader sceneLoader

### ISSUE THREAD

**Issue by NoxMortem** [ssannandeji/Zenject-2019#308]
In my ProjectContext I have a Installer creating a LevelController

```c#
Container.Bind<LevelController>().AsSingle().NonLazy();
```
I want that LevelController uses `ZenjectSceneLoader`, but I am unable to inject it properly. If I don't bind `ZenjectSceneLoader` it can't resolve the type, which is expected. However, when I try to bind it at the ProjectContextInstaller with

```c#
Container.Bind<ZenjectSceneLoader>().AsSingle();
```

It says there are multiple matches. When I try to call this line from the Installer of my SceneContext it says it is unable to resolve type `ZenjectSceneLoader` when building LevelController, which is also expected as it can't find a binding for it during the ProjectContext. However, I have no idea how to resolve the dependency.

**Comment by Chaser324** [comment]
You shouldn't bind ZenjectSceneLoader yourself. Every SceneContext binds its own instance of ZenjectSceneLoader.

Also, ZenjectSceneLoader itself requires a SceneContext be injected into it, so you're not going to be able to inject it into anything you're binding at the ProjectContext level. If you need to do something like this, consider [scene parenting](https://github.com/modesttree/Zenject#scene-parenting-using-contract-names) or scene decorators instead of using ProjectContext.
