### ISSUE TITLE
Unable to recreate MonoBehaviour Factory example

### ISSUE THREAD

**Issue by NoxMortem** [ssannandeji/Zenject-2019#310]
```c#
//Player.cs
public class Player : MonoBehaviour {}

//LevelController.cs
public class LevelController{
private Player _player;
public LevelController(Player player){_player = player;}
public class PlayerFactory : Factory<Player> { }
}

//FactoryInstaller.cs
public GameObject PlayerPrefab;
public override void InstallBindings()
{
     //Bind Factories
    Container.BindFactory<Player, LevelController.PlayerFactory>().FromComponentInNewPrefab(PlayerPrefab).WithGameObjectName("Player");
    Container.Bind<Player>().AsSingle();
}

```

Throws
```
Assert hit! Error occurred while instantiating object of type 'Model.Player'. Instantiator should not be used to create new mono behaviours.  Must use InstantiatePrefabForComponent, InstantiatePrefab, or InstantiateComponent.
```

This looks for me exactly like the `Enemy : MonoBehaviour` factory example, but I can not get it to work. Any help appreciated.

**Comment by Chaser324** [comment]
The issue is the `Container.Bind<Player>()` line. As the error states, you're trying to bind a MonoBehavior as if it were a regular class. Any time you want to bind a MonoBehavior, you need to be getting or adding it as a component on a new GameObject, an existing GameObject, or on a prefab - this is what the `FromComponentInNewPrefab` call in your code is doing.

Take a look back at the example and take note that `Player` is just a standard class and `Enemy` is a MonoBehavior that is being instantiated through a factory. It looks like you kinda mixed up those two classes or tried to merge them together without noting the differences.
