### ISSUE TITLE
UnbindInterfacesTo<T>() ??

### ISSUE THREAD

**Issue by mikecann** [ssannandeji/Zenject-2019#312]
Hi,

Suppose I have the following class.

```
class MyLogger : :ILogger, IInitializable
{
    ...
}
```

Then I bind it in an installer like:

```
Container.BindInterfacesTo<MyLogger>().AsSingle();
```

All is well and good, but what happens if later in the execution (perhaps in a child container) I want to rebind the logger to my new class:

```
class MySuperLogger : ILogger, IInitializable
{
    ...
}
```

I can do:

```
Container.Rebind<ILogger>().To<MySuperLogger>().AsSingle();
```

But unfortunately the `Initialize()` in `MyLogger` still gets invoked because you havent removed the binding, how is one to remove that binding?

What we need really is the inverse of `BindInterfacesTo<T>`, we need an `UnbindInterfacesTo<T>`..

Do you have a suggestion how one might go ahead wit implementing that?

Cheers,
Mike

**Comment by svermeulen** [comment]
We could add an `UnbindInterfacesTo<T>` method but it wouldn't work like how you're expecting, since it would unbind everything that is bound to the given interface and not just the bindings related to T.

Using Unbind and Rebind in general is kind of a bad idea in my opinion.  I would recommend using flags to avoid adding the undesirable binding in the first place.  Also, you mentioned that you might want to change the binding later on during execution.  I should mention that it's bad practice to add or modify bindings after the "install phase" is completed.

As for child containers, you can actually just use `Bind()` or `BindAllInterfacesTo<>` with the the super logger class instead of Rebind or Unbind.  This is because any class that asks for an instance of `ILogger` will always map to the binding in the lower level container first, before falling back on higher level containers.

**Comment by mikecann** [comment]
Hi Svermeulen, thanks for your reply.

>  I would recommend using flags to avoid adding the undesirable binding in the first place

What do you mean by flags?

Perhaps I used a bad example my mentioning multi-scenes, the problem actually stems from when you are using the same SceneContect but with multiple Installers.

If you have an installer on your SceneContext that Binds `MyLogger` then in the next installer in the list you want to bind `MySuperLogger`, you first have to unbind `MyLogger` from `ILogger` before you can bind `MySuperLogger` but then we are back to the same problem that IInitializable is still called in MyLogger.

You might argue "well dont add the first Installer to the SceneContext, and thus not add the MyLogger binding". Well, we like to break our sub-systems in our app up into different libraries and its convenient to use installers in those libraries so that the project that wants to use that sub-system can just installer the installer and get all the dependencies. So it would just have been convenient to "rebind" just one of the dependencies instead of having to copy-paste all but one of the dependencies from the offending installer.

I hope this makes sense.

Im wondering with `UnbindInterfacesTo<T>` is Zenject not able to introspect all its current bindings and just remove any interfaces that are bound to the concrete type <T> ?

**Comment by svermeulen** [comment]
You're right, now that you mention it, we can selectively unbind the specific bindings that map to a given concrete type.  Sounds more reasonable as a change so I went ahead and added `UnbindInterfacesTo<>` and pushed it to master branch.  Let me know if you run into issues with it.

**Comment by mikecann** [comment]
Wooo! Thats awesome thanks, ill be sure to check it out soon!
