### ISSUE TITLE
Development tests not compiling on unity 2017

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#314]
While working on #313 I've updated unity to 2017.1.0f3
And they have updated NUnit so that `[ExpectedException]` is no longer supported.
I've rewritten the tests so that they pass. Should I create a pull request? Should it include ProjectVersion.txt etc?
Should it include automatically updated shaders?

**Comment by svermeulen** [comment]
Were you working off of the develop branch?  I noticed while merging your PR that you were.  I don't always keep that branch up to date, except for cases where I'm working on a really large feature.  It is up to date now however.  I mention this because there was a fix on master that addressed the ExpectedException error.

**Comment by marsermd** [comment]
I was working on the develop branch, I beleive that somebody told me to do so. But I'm not sure if it was you:)
