### ISSUE TITLE
Instantiate prefab declared with FromComponentInNewPrefabResource() after initial injection.

### ISSUE THREAD

**Issue by PhilippCh** [ssannandeji/Zenject-2019#317]
Hi there!

I'm declaring some reusable prefabs using a custom installer like this:

`Container.BindInterfacesAndSelfTo<ToolTip>()
				.FromComponentInNewPrefabResource(Paths.PREFABS_UI + "/components/tooltips/tooltip")
				.AsSingle();`

I know I can request them using `[Inject]`, but is it also possible to grab them after the initial injection run through DiContainer?

Cheers
Philipp

**Comment by Chaser324** [comment]
It sounds like what you actually want is a factory. A factory would allow you to create instances of the prefab at will without having to do something messy that you really shouldn't.

```csharp

// Tooltip.cs
public class Tooltip : MonoBehaviour
{
    ...

    public class Factory : Zenject.Factory<Tooltip>
    {
    }
}

// CommonInstaller.cs
Container.BindFactory<Tooltip, Tooltip.Factory>().FromComponentInNewPrefab(tooltipPrefab);

// TooltipUser.cs
[Inject]
private Tooltip.Factory tooltipFactory;

public void Foo()
{
    Tooltip aNewTooltip = tooltipFactory.Create();
}
```

If you're going to be creating/destroying these frequently, you may want to consider using a pool instead of a factory.

For more info, consult the documentation:
* https://github.com/modesttree/Zenject/blob/master/Documentation/Factories.md
* https://github.com/modesttree/Zenject/blob/master/Documentation/MemoryPools.md
