### ISSUE TITLE
Support for nested composition roots (contexts)

### ISSUE THREAD

**Issue by MaximumViciousDeer** [ssannandeji/Zenject-2019#33]
I am making a spaceship game which currently doesn't use DI, but I have read a lot about Zenject and would like to use it. Some basic info about my game:
- Each player has one ship.
- Ships can be docked inside bigger ships.
- Local co-op support.

I was thinking about making each ship a composition root - that way I could inject ship configuration, player input etc. to the ship's submodules (which are sub transforms of the ship). The ship may be nested when docked.
This does however not seem to be entirely achievable using Zenject.
How would you use Zenject in this case?

**Comment by MaximumViciousDeer** [comment]
Perhaps I could use conditional injection, doing something like:

``` C#
foreach (var player in players)
{
    int playerID = player.ID;
    PlayerInput input = player.Input;

    Container.Bind<PlayerInput>().ToInstance(input).When(c => 
        ((MonoBehaviour)c.ParentInstance)
        .transform
        .root
        .GetComponent<Ship>()
        .Player
        .ID == playerID
    );
}
```

Which could be used to inject the input object for all modules of a ship.

Is it possible to redo injection at a later stage (long after object creation)? Say I create a ship module at start and later on it changes owner, could I redo the injection to get a new player input instance?

**Comment by svermeulen** [comment]
Zenject does have some very basic support for nested containers.   I actually find them very useful.  It's nice because you can declare dependencies as singleton's that only exist within the sub-container, and you don't have to use a bunch of complex conditional bindings (although that would work as well)

You can read about it in the docs here:
https://github.com/modesttree/Zenject#nested-containers

However, it's not as simple as adding a CompositionRoot component to a prefab.  As I said, I have plans to extend support for this kind of thing but for now it's quite basic.  

Honestly, you are probably better off using conditional bindings.  Using nested containers probably adds more complexity to the problem than it takes away.  But if you insist on doing it that way, something like this might work:

``` csharp
public class ShipFactory
{
    DiContainer _mainContainer;

    public ShipFactory(DiContainer container)
    {
        _mainContainer = container;
    }

    public Ship Create()
    {
        var subContainer = new DiContainer();

        // This will allow any classes within your subcontainer to 
        // access root-level bindings
        subContainer.FallbackProvider = new DiContainerProvider(_mainContainer);

        subContainer.Install<ShipInstaller>();
        subContainer.Bind<PlayerInput>().ToSingle();
        // etc.
        // Add other bindings

        return subContainer.Instantiate<Ship>();
    }
}
```

As for redoing injection at a later stage, you can call Container.Inject() to do this but it is kind of against good DI practices  :)  So I would recommend a different approach there

**Comment by MaximumViciousDeer** [comment]
Thanks, great information!
How are the containers scoped? If I create one or several sub (nested) containers, can I specify their domain - such as a transform hierarchy or namespace? Or are they global and executed in their own hierarchy order (fallbacks), until one can inject the dependency?

**Comment by svermeulen** [comment]
Hey sorry for the late response

The nested containers have no scope really. The way it works is that the Container will only 'fallback' on using it's parent container if it can't find any matches in it's own bindings.

**Comment by svermeulen** [comment]
I finally added much better support for nested containers.  I even used your example of a space ship game in the documentation  :)

I haven't merged this yet but if you're interested you can check it out on the [develop branch](https://github.com/modesttree/Zenject/tree/develop).  The README contains new sections on sub-containers.  I'll close this item when I merge it in

**Comment by MaximumViciousDeer** [comment]
Cool! Thanks for following up on this :)
