### ISSUE TITLE
MemoryPool is bound as singleton

### ISSUE THREAD

**Issue by charlotterocklyn** [ssannandeji/Zenject-2019#342]
I have two instances of the same class which I'm injecting a MemoryPool into. However this MemoryPool seems to be injected as a singleton even though it was not specified in the binding. Should the MemoryPool be instantiated as a transient by default or is there a way to specify this that I have missed?

**Comment by svermeulen** [comment]
Factories and MemoryPools are always bound `AsCached` currently.  There isn't a way to change this right now but a fix is planned as described in issue #332 .  Don't you normally want to use the same memory pool though?

**Comment by charlotterocklyn** [comment]
Yes, we are using the separate memory pools for a very specific unrelated issue, we could probably look into a better solution to that problem. Thanks.

**Comment by svermeulen** [comment]
Closing since I can't think of any valid use cases for Factory<> or MemoryPool<> derived classes to be bound as transient

**Comment by Split82** [comment]
I have a very specific reason why I would like to have transient **MemoryPool**.
My spawned objects have some events and normally the object which spawns them (let's call it **Spawner**) would just subscribe to those events when Spawn is called and unsubscribe when Despawn is called. This pattern is nice and clean, but some memory is allocated on heap if there is more than one event subscriber.

So instead of subscribing and unsubscribing each time the object is Spawned / Despawned, subscription happens only in the beginning. This can work only if **Spawner** has full control over its **MemoryPool**.

Maybe there is a also a different (and better) solution to this problem, but right now I can't find any.

**Comment by svermeulen** [comment]
Ok that's fair, we could add a way to override AsCached.

Here's a workaround that might work for you in the meantime

```csharp
Container.Bind<Foo.Pool>().FromSubContainerResolve().ByMethod(subContainer =>
    {
        subContainer.BindMemoryPool<Foo, Foo.Pool>();
    })
    .AsTransient();
```

**Comment by svermeulen** [comment]
Ok this is fixed now on LTS branch.  Factories and Memory Pools will be default be AsCached but you can force transient by adding AsTransient
