### ISSUE TITLE
UniRx signal integration doesn't work with .net 4.6

### ISSUE THREAD

**Issue by tertle** [ssannandeji/Zenject-2019#344]
**Issue**
The UniRx signal integration (ZEN_SIGNALS_ADD_UNIRX) doesn't work in Unity 2017.x with UniRx because UniRx moved to conditionally using System.IObservable<T>

Source from UniRx IObservable
```
using System;

#if !(NETFX_CORE || NET_4_6)

namespace UniRx
{
    public interface IObservable<T>
    {
        IDisposable Subscribe(IObserver<T> observer);
    }
}

#endif
```

In the SignalX classes, zenject references IObservable directly from UniRx

Signal0, Line 30
```
#if ZEN_SIGNALS_ADD_UNIRX
        public UniRx.IOZbservable<Unit> AsObservable
        {
            get
            {
                return _observable;
            }
        }
#endif
```

**Solution**
Easy fix. Remove the UniRx namespace from IObservable
```
#if ZEN_SIGNALS_ADD_UNIRX
        public IObservable<Unit> AsObservable
        {
            get
            {
                return _observable;
            }
        }
#endif
```

You already reference the UniRx namespace in the signal class.

**Note**
This also applies to the UniRx.Tuple<TParam1, TParam2> refernces in the Signal2 onward classes.

**Comment by svermeulen** [comment]
Some observations from a very brief look I took at this today:

I noticed that the copy of IObservable.cs within UniRx that I get when I install it from the asset store is different from the copy in the source code rep [here](https://github.com/neuecc/UniRx/blob/master/Assets/Plugins/UniRx/Scripts/System/IObservable.cs).  The defines that are used to include the UniRx version of IObservable are different.  The code you posted appears the same as what's directly in the repo instead of the version froma sset store.

Also, it doesn't seem like the fix is as simple as removing UniRx when referencing IObservable, since you get ambiguous reference errors in this case when you set scripting runtime to 4.6

I'm also unclear on how to reproduce this issue since I'm unclear on how to get UniRx to not define the IObservable class when installed from asset store

**Comment by tertle** [comment]
I should have mentioned that sorry. 

neuecc hasn't really committed much to UniRx in a while (busy with other projects.)
He hasn't pushed a new build on the assetstore or done a release since Sep 30, 2016.
The most recent assetstore and release doesn't work with .net 4.6 

However he did commit changes to UniRx to give it .net 4.6 support on July 6th 2017
https://github.com/neuecc/UniRx/commit/6ea038d114ffa1f709eeb6ebc2701de8d0248ee4
The only way to get it is to pull from repo.

So yeah I'm not really sure what a good solution is since it's not the actual release build (but again current release build doesn't actually work in .net 4.6 so pulling is only way to have UniRx work.)

I've updated it in my own project so it all works fine as I don't care about .net 3.5 support.
I just thought it should be something you were aware of for when/if the fix is pushed to assetstore.

**Comment by svermeulen** [comment]
Ah yes I understand what you mean now.  It seems like the version of UniRx that you install from asset store does compile properly and work when using .net 4.6, but it's painful because it still uses UniRx.IObservable everywhere so you have to explicitly reference that in any code that includes namespace System and namespace UniRx in the same file.

So we could change `UniRx.IObservable` to just `IObservable` in the signal classes.  But then that would only work with the copy of UniRx from the github repo and would break when trying to use it with the copy of UniRx that's in asset store...

So I think we should probably just wait for UniRx to update the asset store version with the `NET_4_6` if statement that you pasted above before making any change on our side

**Comment by ryanleecode** [comment]
Whats the current solution to this? I keep getting `Observable.AsObservable<T>(IObservable<T> is not a method, which is not valid in the given context` whenever I try to subscribe to it.

**Comment by svermeulen** [comment]
I believe this is fixed now that UniRx has updated the asset store version
