### ISSUE TITLE
Binding interfaces to objects created with factories?

### ISSUE THREAD

**Issue by suzdalnitski** [ssannandeji/Zenject-2019#351]
I have the following code:

```
public class Updater : ITickable
{
    public class Factory : Factory<Updater> { }
}
```

Is it possible to bind ITickable interface to objects created with factories? Thank you.

**Comment by zaniar** [comment]
Do you mean that you want ITickable instance to be injected to dynamically created objects?  
If that is what you meant, the answer is yes. Just do it normally.

**Comment by svermeulen** [comment]
You cannot add bindings like ITickable to dynamically created objects since that would change the container after the install phase is complete.  You have to create a manager class and bind that to ITickable, and have that explicitly call Tick().  This is also explained in the [gotchas section](https://github.com/modesttree/Zenject#di-guidelines--recommendations)
