### ISSUE TITLE
Add "params object[]" overload to IInstantiator.Instantiate extraArgs

### ISSUE THREAD

**Issue by whatwapp** [ssannandeji/Zenject-2019#357]
when using "Instantiate()" to create objects with extra args, it would be useful to have an overload of that method that takes a ”params object[]" argument for it.

**Comment by svermeulen** [comment]
This might work with `DiContainer.Instantiate` but would not work with some of the other instantiate methods because they have overloads that take more parameters than just the argument list (so it would be ambiguous compared to just a params object[] argument).  So we could do this but:

- It would be inconsistent with other Instantiate methods
- If we wanted to add method overloads after making this change it would not be possible without adding a different method
- Using a collection is also consistent with other ways of instantiating things in .NET (eg. Activator.CreateInstance)
- It already works this way so would be a breaking change for existing users

So I would prefer to keep it an explicit collection for all the instantiate methods for now.

**Comment by whatwapp** [comment]
Hi,
I was recently bitten by the fact that if you declare a single arg with "new[]{whatever}", mono creates an array of the actual type, compiles and runs fine on mono, but throws on IL2CPP (because it can't convert from `IEnumerable<MyClass>` to `IEnumerable<Object>`).
params would have created an actual object[].

maybe add a note somewhere about this.

**Comment by svermeulen** [comment]
Ok, I added a comment above each Instantiate warning about this on develop branch, thanks.
