### ISSUE TITLE
lazy instantiation of objects

### ISSUE THREAD

**Issue by bbdb68** [ssannandeji/Zenject-2019#36]
lazy instantiation of object would allow creation of objects only if they are injected into other one.

**Comment by svermeulen** [comment]
This is how it should work.  Can you explain the case in which you are seeing this?

**Comment by bbdb68** [comment]
thinking about it, this is probably because the object is also IInitializable. Will make a test asap.

**Comment by bbdb68** [comment]
My mistake, Zenject is effectively lazy, but the object we considered was effectively IInitializable. When removing the initialization, the object is not instantiated

**Comment by svermeulen** [comment]
Yep, exactly.  The InitializableManager has a dependency on all IInitializables and the UnityDependencyRoot has a dependency on InitializableManager so it's always created on startup.

**Comment by svermeulen** [comment]
You might want to use [PostInject] instead which will keep it being lazily instantiated, but [PostInject] will be called in the middle of the construction of the initial object graph, so that may not be ideal.

I prefer using IInitializable for startup objects so that initialization occurs after the complete construction of the initial object graph, and also so that I can explicitly control the order that objects are initialized in, in case I need that.
