### ISSUE TITLE
Add support for using FromMock with factories and memory pools

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#360]
Something like this should work:

```
public static class ZenjectMoqExtensions
{
    public static ConditionCopyNonLazyBinder FromMock<TContract>(this FactoryToChoiceIdBinder<TContract> binder)
    {
        return binder.FromInstance(Mock.Of<TContract>());
    }

    public static ConditionCopyNonLazyBinder FromMock<TContract>(this MemoryPoolInitialSizeBinder<TContract> binder)
    {
        return binder.FromInstance(Mock.Of<TContract>());
    }
}
```

Then you can use it like this:

```
public class TestInstaller : MonoInstaller<TestInstaller>
{
    public override void InstallBindings()
    {
        Container.Bind<Foo>().FromMock();
        Container.BindFactory<Foo, Foo.Factory>().FromMock();
        Container.BindMemoryPool<Bar, Bar.Pool>().FromMock();
    }
}
```

**Comment by raveneer** [comment]
compile error.

Assets/Plugins/Zenject/Source/MockFacory/MoqExtension.cs(10,41): error CS0452: The type `TContract' must be a reference type in order to use it as type parameter `T' in the generic type or method `Moq.Mock.Of<T>()'



using System.Collections;
using System.Collections.Generic;
using Zenject;
using Moq;

public static class ZenjectMoqExtensions
{
    public static ConditionCopyNonLazyBinder FromMock<TContract>(this FactoryToChoiceIdBinder<TContract> binder)
    {
        return binder.FromInstance(Mock.Of<TContract>());
    }

    public static ConditionCopyNonLazyBinder FromMock<TContract>(this MemoryPoolInitialSizeBinder<TContract> binder)
    {
        return binder.FromInstance(Mock.Of<TContract>());
    }
}

**Comment by svermeulen** [comment]
Yes, I said something *like* that would work  :P  I didn't actually test it.  I've tested it now though and fixed the error and updated the AutoMocking.zip file

**Comment by Chazmus** [comment]
Woule you be able to add the same thing for NSubstitute?

**Comment by Mathijs-Bakker** [comment]
@Chazmus I added support for NSubstitute a while ago.

So you can do:
``Container.Bind<ICalculator>().FromSubstitute();``

All in one line.

Docs:
https://github.com/svermeulen/Extenject/blob/master/Documentation/AutoMocking.md

Note: It's not merged into this fork of Zenject but in the Extenject fork. (and asset).

**Comment by Chazmus** [comment]
Hi Mathijs, Sorry yes the NSubstitute stuff is brilliant! But I was looking for a way of getting a factory to return a substitute when it's Create method is called - is that bound in a similar way?

**Comment by Mathijs-Bakker** [comment]
Oh, I did't read the whole issue. Only the first 'Add support for using FromMock..' part. XD
Sorry for that.

I don't (or at least often) substitute Factories. But yeah it should work the same way. I don't have the time test it now. But I guess you will ;)

If it doesn't work or you have any troubles. Could you open an issue on the Extenject fork?
With a backward link to this issue here.
