### ISSUE TITLE
TickableManager isPaused performance on nested subcontainer kernels

### ISSUE THREAD

**Issue by tertle** [ssannandeji/Zenject-2019#367]
I noticed while doing some profiling that my FixedUpdate was taking longer than I expected. Apart from some animation stuff, the time it took MonoKernal to call FixedUpdate when I'm not using IFixedTickable anywhere was surprising.

After exploring it a little, it turns out the IsPaused property takes a surprisingly long time to execute.

https://i.imgur.com/stZZcbK.png

This seems to be because I have a few nested subcontainers (due to the stack based state system I'm using.) But this was only 5-6 subcontainers deep and it was already noticeable and I intended to potentially go quite a bit deeper. 

For now I've just removed the property all together as I don't utilize pausing and resuming in my project. I might even remove the kernels entirely from my state stack, I don't really utilize the tick interfaces, it was just there for support.

However, maybe a better solution would be to cache the IsPaused method every frame? I assume (I haven't tested) tickablemanager will be called downwards, therefore something simple like:

```
private bool _isPausedCache;

public bool IsPaused
{
	get
	{
		return _isPausedCache;
	}
}

public void FixedUpdate()
{
	_isPausedCache = CalcIsPaused();

	if (IsPaused)
	{
		return;
	}

	_fixedUpdater.OnFrameStart();
	_fixedUpdater.UpdateAll();
}

private bool CalcIsPaused()
{
	if (_isPaused)
	{
		return true;
	}

	if (_parents.Value != null)
	{
		for (int i = 0; i < _parents.Value.Count; i++)
		{
			if (_parents.Value[i].IsPaused)
			{
				return true;
			}
		}
	}

	return false;
}
```

**Comment by svermeulen** [comment]
Yeah that makes sense, since it's only checked once per frame anyway.  Now that you mention it though, maybe we should just remove IsPaused altogether.  Unity doesn't have an "IsPaused" flag that controls whether Update gets called, so why do we need this?  And you can kinda already do this anyway by disabling the associated MonoKernel component

Also, I can't imagine many people care about the way it inherits the IsPaused flag from its parents, so probably not worth the extra implementation complexity or performance implications that you point out.

**Comment by svermeulen** [comment]
Ok for now I kept IsPaused but it doesn't inherit parent tickable IsPaused state anymore.

If somebody needs that behaviour, then they can use Kernel and not MonoKernel.  Then, when they bind Kernel as an ITickable to the higher level container, this behaviour will happen automatically.

Thanks for reporting this
