### ISSUE TITLE
[Feature] Generating IDs enum

### ISSUE THREAD

**Issue by YuriyVotintsev** [ssannandeji/Zenject-2019#378]
What about using enum dropdown in ZenjectBinding component for Identifier field?
To create new ID user will open IDs inspector (something like Tag or Layer inspector in Unity). After adding (removing/editing) ID Zenject will regenerate enum file with name somethig like "ZenIDs.cs" with all IDs in that list.
And then it will be much easy and less error prone to use ZenjectBinding Identifier field (without "magic strings").

[Inject(Id = ZenIDs.SomeId)]
private Foo _foo;

**Comment by svermeulen** [comment]
You can actually use your own enums with identifiers.  I do this sometimes so that I can do a similar thing in the inject attribute (eg. `[Inject(Id = ZenIDs.SomeId)]`).   This is because identifiers can be any type and not just strings.

For ZenjectBinding however, I think we have to use strings.  I don't know how we could allow other types there.

Also, automatically generating a master enum for all identifiers would be restrictive of a design.  Better to make zenject less intrusive with its design choices
