### ISSUE TITLE
Fallback Containers and Optional Injectables

### ISSUE THREAD

**Issue by bvance** [ssannandeji/Zenject-2019#38]
It looks like you guys decided to make it so 'optional' contexts will not fall back to 'parent' containers should they fail to find an appropriate binding in the base container. Is there any reason you decided to go that way?

I'm working on some experimental code using Zenject and it seems to me like it would be far more helpful if DiContainers searched fallbacks for optional bindings the same as they do for mandatory ones (simply returning null if no bindings are found therein).

**Comment by svermeulen** [comment]
Yes, I agree that it should work that way

The way nested containers work in Zenject still needs some improvement and best practices/etc. still need to be worked out.  Right now, a parent container is treated as a 'fallback'.  I think this is great for single dependencies to allow you to override a binding from a higher-level container in a lower-level container, but for list dependencies I don't think this really makes sense.

Right now, when a dependency of type `List<Foo>` is marked as optional, and there are no Foo's bound to the container, then an empty list is injected.  If there are Foo's bound to a parent container, they will not be added to the list.  It will only look up lists in the parent if the list is not marked as optional and there are no matches in the current container.

However, as I said I think it would be better if lists just always collected all dependencies from the current container and parents.  This way the concept is much more intuitive and you can think of as the nested containers "inheriting" all bindings from their parents rather than using their parent as a "fallback".

There are some changes I need to make to make this happen - in particular, the way the global composition root stuff works.  I will leave this item open until I am able to address it.

Side note:  Having proper support for nested containers would also mean I can get rid of the concept of "Bind Scope" since we can just have a CreateNestedContainer() method and use that instead.  It would also make the DiContainer more thread-safe and just overall be much cleaner

**Comment by bvance** [comment]
The way I use Zenject is bottom-up rather than top-down; so rather than using its provided Unity components, instantiators etc, any of my scripts that require DI must call an 'InjectFields' extension method that then accesses a static factory responsible for providing the DiContainer. (This way I can use Zenject purely through code without having to configure my unity scene objects in any particular way.)

What I've been up to lately involves having this static factory first check through the injectable script's parent hierarchy for anything pointing to a special 'override' DiContainer and, if so, injecting via that thing first (THEN the default one as a fallback). It works fairly well, though it's tedious to automatically/invisibly set up the default one as a fallback.

What might be most helpful for me is if you used nested InjectContexts (or something similar) to build DiContainer hierarchies dynamically at injection time. (Perhaps in addition to nested DiContainers?) That would give me maximum flexibility in terms of how I want to handle the task of deciding which containers to check and in what order.

**Comment by svermeulen** [comment]
Your approach makes me wonder how you can have multiple different bindings/installers for different scenes?  Or perhaps you don't require that for your particular problem.

InjectContexts are nested already (they have a parent InjectContext).  This allows for very complex binding conditions that can depend on parent or grandparent identifiers, etc.  

But I'm not sure how that would apply to your problem.  Can you elaborate on how you imagine that working?

**Comment by bvance** [comment]
My last project did a bunch of crazy additive loading/unloading to achieve a big continuous world (that also ran on mobile); we ended up with about 80 scenes in total, most with extremely homogeneous requirements. I implemented Zenject 2/3rds through the project and didn't want to refactor all the existing work; fortunately it turned out that we only needed one set of bindings/installers for everything, so a static factory pattern worked well enough! (But if I DID need different ones per scene, I could always do so by having my factory check which scene we're currently in and serve a different container based on that.) The nice thing about it was that my scenes remained completely agnostic to the DI solution, but of course there were quite a few downsides as well.

As I understand it, InjectContexts are not currently designed for use in the way I'm thinking. What I mean to suggest is having methods like:

`public object Resolve(InjectContext context, params DiContainer[] extraFallbacks = null) ...`

Permitting you to build dynamic DiContainer hierarchies on a per-injection basis rather than arranging DiContainers into explicit parent/child relationships. Currently I am accomplishing this task using a custom ProviderBase that indirects into a list of DiContainerProviders. It looks essentially like this:

```
public static T DynamicResolve<T>(this MonoBehaviour m, DiContainer overrideContainer) {
    var context = new InjectionContext(overrideContainer, typeof(T), null, false, typeof(MonoBehaviour), m);

    var dynamicContainer = new DiContainer();
    dynamicContainer.fallback = new ZenjectFallbackProvider(StaticallyGetDefaultContainer(), new DiContainerProvider(overrideContainer));
   return  dynamicContainer.Resolve(context);
}

public class ZenjectFallbackProvider : ProviderBase
    {
        ProviderBase Provider;
        ProviderBase Fallback;

        public ZenjectFallbackProvider(ProviderBase fallback, ProviderBase provider)
        {
            Fallback = fallback;
            Provider = provider;
        }

        public override Type GetInstanceType()
        {
            return null;
        }

        public override object GetInstance(InjectContext c)
        {
            var result = Provider.GetInstance(new InjectContext(c.Container, c.MemberType, c.Identifier, true, c.ObjectType, c.ObjectInstance));

            if(result == null) {
                result = Fallback.GetInstance(c);
            }

            return result;
        }

        public override IEnumerable<ZenjectResolveException> ValidateBinding(InjectContext context)
        {
            return Enumerable.Empty<ZenjectResolveException>();
        }
    }
```

I do this so I can loosely-couple whatever override containers my scripts want to create from the default container provided by my static factory (the former should not have to manually assign the latter as a fallback IMO). It's all pretty hinky though.

**Comment by svermeulen** [comment]
I finally added proper support for sub-containers that works how you were initially suggesting

I haven't merged this yet but if you're interested you can check it out on the [develop branch](https://github.com/modesttree/Zenject/tree/develop).  The README contains new sections on sub-containers

**Comment by bvance** [comment]
Looking good! This project always picks the coolest design patterns :D
