### ISSUE TITLE
Use non-unity and unity versions together

### ISSUE THREAD

**Issue by tylorr** [ssannandeji/Zenject-2019#398]
I have a library I am creating that will be used both inside and outside of Unity. When used outside of unity I want to reference the non-unity dll and when I use the library within unity I want to be able to interoperate with the unity version of zenject. 

Currently my solution is to compile my own version of zenject but rename the namespace so that it doesn't clash with the unity version of zenject. Essentially the library and unity source have two different zenject references that can't interoperate.

My only idea is to compile my library to two dlls. One that has a dependency on the non-unity version and one that has a dependency on a unity version of the zenject dll which would also be used by the rest of the unity source. Is something like this achievable?

**Comment by svermeulen** [comment]
I think that would work.

Do you have any classes that you want to use both outside unity and inside unity?  In that case, you might run into issues because you would need to use both versions of the `[Inject]` attribute every time, which might be tedious.

So you might want to compile the classes in the Usage directory at `Assets\Plugins\Zenject\Source\Usage` into its own DLL, and then use that for both versions of zenject.  The files there includes all the attributes you might include in any using code as well as interfaces like `ITickable` (which might not matter in your non unity code depending on how you're doing it)

**Comment by svermeulen** [comment]
Also, you say that your library is compiled to two dlls.  How is this possible?  The version of zenject used in unity does not come in DLL form, so in order to do what you're saying, I think you'd have to include the source of your library inside your unity project, and then also compile that same code as a dll for non-unity.  So you'd only need one dll for your library (for outside unity)

**Comment by tylorr** [comment]
I'll try pulling the contents of the Usage folder into a dll and see if that fixes my issue. Otherwise I think you are right, I'd have to pull my library source into unity.

**Comment by svermeulen** [comment]
There was a time when zenject supported being built as a dll for unity, but it became impossible once we started using different platform specific defines.  Similarly with using UNITY_EDITOR define.  So we would have had to to compile two dlls for each platform that we used a define with (eg. Zenject-IL2CPP.dll, Zenject-IL2CPP-Editor.dll, Zenject-WSA.dll, Zenject-WSA-Editor.dll, etc.) and then make sure to check the correct checkboxes in the inspector for each dll so unity knew which dlls to use.  This is doable but a huge maintenance headache and also adds a lot of bloat to the install so we decided against it

**Comment by joshbayley** [comment]
Hello,

I have a multiplayer game, client library is unity independent and I'd like it to use zenject (non unity version). From your last post I'm assuming I won't be able to import zenject.dll into unity and maintain platform support?

**Comment by svermeulen** [comment]
No, you can't import zenject.dll into unity due to the reasons I mention above.  Zenject needs to be compiled by unity so that it can use all those preprocessor defines.

But it would be nice if we could more easily support writing code that works with both the non-unity zenject and zenject as compiled by unity

Usually this should work fine because if you use construction injection then any code you write does not need to depend on the zenject dll, so will work with zenject both inside and outside of unity.  But if you do things like use field injection, method injection, or property injection then you need to use the `[Inject]` attribute which is inside the zenject DLL.   Similarly if you want to make use of interfaces like ITickable, IInitializable, etc.

But we could easily wrap that stuff up in its own DLL (eg. zenject-usage.dll) and have the zenject dll depend on that, and then also include it inside unity.

One thing that might be annoying though is that you won't be able to have installers inside your own dll, because installers need to use the DiContainer which makes use of all these preprocessor defines.

I think it would also be worth actually checking to see how many of these preprocessor defines could be converted to runtime checks.  Maybe it wouldn't be that much work.  If enough people wanted it we could provide the full zenject dlls as an alternative potentially.

**Comment by joshbayley** [comment]
I do only need construction injection for my client library, having to explicitly install all dependencies in the consuming project is a small price to pay really. This means I can make use of zenject in my unity project as well as in my unity independent (headless bots) project.

Many thanks for your response and clarification!

**Comment by svermeulen** [comment]
Ok I made this change on the develop branch so will be in zenject 6.  You can now reference Zenject-usage.dll in dlls outside unity and then use `[Inject]` attribute as well as the interfaces like `ITickable` etc.

**Comment by felipeprov** [comment]
Great news!
I will give it a try this week!

**Comment by tnelling** [comment]
@svermeulen Can you explain a little bit more how to do this?

My (desired) setup is that I have a bunch of class libraries compiled outside of Unity which then get dropped into the Plugins folder, and some of them reference Zenject. And of course I need to use Zenject components in Unity as well.

Do I still need to have Unity compile the Zenject source? Does Zenject-usage.dll need to be available in the Unity Plugins folder?

EDIT: I'd also like to be able to use Zenject with some of the same class libraries for DI on a server that would not be running inside Unity, if possible.
