### ISSUE TITLE
FromComponentInHierarchy missing when using BindInterfacesAndSelfTo method

### ISSUE THREAD

**Issue by svermeulen** [ssannandeji/Zenject-2019#407]

**Comment by johnlcox** [comment]
I could probably send a pull request for this.

Would using this method look like below since `BindInterfacesAndSelfTo` returns a `FromBinderNonGeneric`?

``` C#
Container.BindInterfacesAndSelfTo<Foo>().FromComponentInHierarchy<Foo>();
```

What about these methods too:
* `FromComponentInSibling`
* `FromComponentInParents`
* `FromComponentInChildren`

**Comment by svermeulen** [comment]
No I don't think a generic argument is needed to the FromComponentInHierarchy method.  It should use the same generic argument provided to BindInterfacesAndSelfTo.

`BindInterfacesAndSelfTo<Foo>` is equivalent to: `Bind(typeof(Foo), typeof(IFoo), etc.).To(typeof(Foo));`

So when you add `FromX` to that it should use the type provided to the `To()` method.

I took a quick peek at this just now.  If you want to take a crack at it, probably the easiest thing to do would be to copy and paste these missing methods from FromBinderGeneric into FromBinderNonGeneric then change them to maybe use FromMethodMultipleBase<Component> and the ConcreteTypes list instead of TContract?

**Comment by svermeulen** [comment]
And then probably not bother with adding support for the optional predicate argument

**Comment by johnlcox** [comment]
When using `FromMethodMultipleBase` I can only get it to infer the method as `Func<InjectContext, IEnumerable<Component>` since the non-generic method `GameObject.GetComponentsInChildren` returns `Component[]` rather than `T[]` like the generic version. This leads to the assertion in the `FromMethodMultipleBase` failing.

One idea I have for resolving this is to have a non-generic `FromMethodMultipleBase` along with a new provider like `MethodProviderMultipleUntyped`. I'm not sure if this would actually solve anything or if there is a better option.

I don't actually need this functionality. I was hoping to take this as an opportunity to help out with a project I really like using and to learn more about the internals. If it's going to be too much effort on your part to go back and forth and help point me in the right directions, then I can leave this for you to work on since you have much deeper knowledge of the internals than I do.

**Comment by svermeulen** [comment]
As it turns out it was quite a bit more complicated than I thought to add this, but it's added now
