### ISSUE TITLE
use default constructor if more than one found and none have injectors

### ISSUE THREAD

**Issue by lacostej** [ssannandeji/Zenject-2019#416]
(Related to #7)

If Zenject finds more than one constructor, and none are explicit, it fails by default.

````
ZenjectException: Assert Hit! Found null pointer when value was expected. More than one (or zero) constructors found for type 'WWTK.Persistence.DataPersistence' when creating dependencies.  Use one [Inject] attribute to specify which to use.
ModestTree.Assert.Throw (System.String message) (at Assets/UPackages/Zenject-WithSampleGames~5.2.2/Internal/Assert.cs:269)
ModestTree.Assert.IsNotNull (System.Object val, System.String message, System.Object[] parameters) (at Assets/UPackages/Zenject-WithSampleGames~5.2.2/Internal/Assert.cs:200)
Zenject.DiContainer.InstantiateInternal (System.Type concreteType, Boolean autoInject, Zenject.InjectArgs args) (at Assets/UPackages/Zenject-WithSampleGames~5.2.2/Main/DiContainer.cs:815)
Zenject.DiContainer.InstantiateExplicit (System.Type concreteType, Boolean autoInject, Zenject.InjectArgs args) (at Assets/UPackages/Zenject-WithSampleGames~5.2.2/Main/DiContainer.cs:2178)
````
https://github.com/modesttree/Zenject/blob/0337b58/UnityProject/Assets/Plugins/Zenject/Source/Util/TypeAnalyzer.cs#L280-L287

Yet if there's a default constructor, Zenject could select it.

In our use case, we would like to inject an instance of an existing class with existing constructors with arguments. This will obviously not work. We decided to modify our API to be more injection friendly and add a default constructor without arguments and explicit setters that we can call in our `MonoInstaller` instance. We would also like that library to stay Zenject free, so adding the [Inject] attribute is not an option.

But Zenject will not default to the new argument-less constructor and instead fail.

Falling back on the default argument-less constructor, the only one usable from Zenject, would allow us to stay backwards compatible.

**Comment by svermeulen** [comment]
I'll see if I can address #7, I think it should be doable and that would be a better fix

**Comment by svermeulen** [comment]
Although even in that case you have to choose a strategy which might not be obvious necessarily.  So something simple like 'choose the constructor with the least parameters when [Inject] attribute is missing' might be preferable to throwing an exception for now.  Even though that would allow you to accidentally add constructors and get less obvious null ref exceptions or something instead

**Comment by johnlcox** [comment]
Rather than trying to choose a constructor would it be possible to add an explicit binding to a particular constructor through the Zenject binding DSL similar to how Guice works? Guice also selects a constructor that is not annotated with `Inject` if there is only one constructor, but if there are multiple it allows using `toConstructor(java.lang.reflect.Constructor<S>)` [1].

A quick Google search indicates that C# reflection also supports references to constructors [2].

The advantage of doing it this way is that it's explicit and allows using Zenject with classes from libraries that are out of the control (to change) for the developer writing the application.

This might look something like:

``` C#
Container.Bind<Foo>()
    .ToConstructor(typeof(Foo).GetConstructor(new Type[] { typeof(string) }));

Container.Bind<IFoo>()
    .To<Foo>()
    .WithConstructor(typeof(Foo).GetConstructor(new Type[] { typeof(string) }));

// or (by abstracting the call to `ToConstructor`)

Container.Bind<Foo>()
    .WithConstructorParameters(typeof(string), typeof(float));

Container.Bind<IFoo>()
    .To<Foo>()
    .WithConstructorParameterss(typeof(string), typeof(float));
```

[1] https://google.github.io/guice/api-docs/latest/javadoc/com/google/inject/binder/LinkedBindingBuilder.html#toConstructor-java.lang.reflect.Constructor-
[2] https://msdn.microsoft.com/en-us/library/system.type.getconstructor.aspx

**Comment by svermeulen** [comment]
Ok I decided to fallback on using the constructor with the least amount of arguments when forced to make a choice.  I think this makes sense since it allows usage with libraries that don't depend on zenject even though it could result in more subtle error behaviour in some cases. 

This is committed to develop branch and will be in the next version

@johnlcox I moved your other suggestion to its own issue #417
