### ISSUE TITLE
Performance issue on Scene change

### ISSUE THREAD

**Issue by Crabar** [ssannandeji/Zenject-2019#428]
Hi there!
I have a two scenes: Menu and Main. And I have a huge lag on `SceneManager.LoadScene("Main")`. In the Editor it is about 0.5 - 1 second, on devices (Android phones) may be up to 2 seconds.
Looks like it is related to Zenject.
Here is a data from profiler: https://gyazo.com/da116d1f8e9b429e9170bc3769d23ac4
The scene has about 40 gameobjects at runtime.
[Scene installer.](https://github.com/Crabar/Craberoid-3.0/blob/master/Assets/Scripts/Installers/MainMonoInstaller.cs)
I am using Unity 2017.2.1f1, .NET 4.6 and Zenject 5.5.1.
Full code is [here](https://github.com/Crabar/Craberoid-3.0).
Are there a ways to speed up switching between scenes?

**Comment by svermeulen** [comment]
I took a look at your game and tried to dig into it a bit.  I also tested with zenject 6 since there was some optimizations there, but for your game the improvement was only marginal.

I couldn't really isolate one specific reason for the lag.  Also I should mention that inside Resolve() it will also instantiate all the objects added through bindings, and also call [Inject] so your code could be executing in there as well.  I did find that the reflection ate up a pretty sizable chunk in this case (~40%) and that's fairly unavoidable right now.  So I'm not really sure what to suggest.  Can you use a loading screen?

**Comment by Crabar** [comment]
Thank you for an answer. Yeah, pretty sure I can use loading screen. It's strange that these problems appearing only in my game though it's pretty small.
