### ISSUE TITLE
Performance improvement.

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#429]
As it happens, I've reached a point when instantiating a game object takes ~100 ms in editor, which is obviously not desirable.

Obviously, I could switch from Factory to MemoryPools, but it looks more like hiding the problem rather than solving it. So I'm going to optimize Zenject.

Over the last few days I've been reading and profiling the source code and there seems to be some room for improvement.

The benchmark:
``` C#
[RequireComponent(typeof(Text))]
public class BenchmarkSubcontainers : MonoBehaviour
{
    private class A1  { };
    // classes A2 ... A29
    private class A30 { };

    private interface INonGeneric
    {
    }

    private interface IGeneric<T>: INonGeneric
    {
    }

    private class GenericFoo0<T> : IGeneric<T>
    {
        [Inject]
        void Init()
        {
        }
    }

    private class GenericFoo1<T, T1> : IGeneric<T>
    {
        [Inject]
        IGeneric<T1> t1;

        [Inject]
        void Init()
        {
        }
    }

    private static Type[] m_GenericFoos = new Type[]
    {
        typeof(GenericFoo0<A1>),
        typeof(GenericFoo1<A2, A1>),
        typeof(GenericFoo1<A3, A2>),
        //typeofs <A4, A3> ... <A29, A28>
        typeof(GenericFoo1<A30, A29>),
    };

    private DiContainer _container = new DiContainer();

    void Update()
    {
        // Allow all the initialization to complete
        if (Time.frameCount == 10)
        {
            RunBenchmark(BindFromSubcontainer, "bind subcontainer");
        }
    }

    private void BindFromSubcontainer()
    {
        int typesCount = m_GenericFoos.Length;
        for (int i = 0; i < typesCount; i++)
        {
            _container.Bind<INonGeneric>().To(m_GenericFoos[i]).
                       FromSubContainerResolve().
                       ByMethod(new SubClass().SubSubcontainerBind).
                       AsSingle();
        }
        _container.ResolveAll<INonGeneric>();
    }

    private class SubClass
    {
        public void SubSubcontainerBind(DiContainer sub)
        {
            int typesCount = m_GenericFoos.Length;
            for (int i = 0; i < typesCount; i++)
            {
                sub.BindInterfacesAndSelfTo(m_GenericFoos[i]).AsSingle();
            }
        }
    }

    private void RunBenchmark(Action action, String benchmarkName, int warmups = 1, int measures = 5)
    {
        //warm-up
        for (int i = 0; i < warmups; i++)
        {
            _container = new DiContainer();
            action();
        }

        long elapsed = 0;

        // benchmark
        for (int i = 0; i < measures; i++)
        {
            _container = new DiContainer();

            Stopwatch sw = new Stopwatch();
            sw.Start();

            action();

            sw.Stop();
            elapsed += sw.ElapsedMilliseconds;
        }
        GetComponent<Text>().text += "running " + benchmarkName + " took " + elapsed / measures + " ms\n";
    }
}
```
This benchmark creates 30 sub-containers with 30 classes bound in each. 
One class is resolved from each sub-container.
This means that `1+2+...+30 = 30*31/2 = 465` classes are instantiated with maximum of 1 dependency per instance.

This results in ~80ms of execution time in the editor and ~50 ms in standalone build on an Intel i5 760.

The most challenging part is determining what is slowing down the code. There is no single function that takes a lot of time solely by itself, there are a lot of small time consumers:) But if you are aware of some parts that take longer than optimal to compute, please let me know.

The first step is to deal with the excessive use of coroutines/IEnumerator in `TryGetUniqueProvider`.
It is called a lot of times and should always return only one answer or throw an exception (all calls to this function throw an AssertionException if received multiple instances. And the name itself implies that a **unique** provider should be returned). 
But `TryGetUniqueProvider` acts as a universal provider search function, which leads to unnecessary coroutine call and ToList() call.

Obviously, only those changes will be made that don't affect behaviour.

@svermeulen, what do you think? Any suggestions/warnings/...?

**Comment by svermeulen** [comment]
Thanks for looking into this!   I've been working on develop branch to try and address some of the performance issues.  In the past, like you mentioned, I've always suggested using memory pools and hiding the lag with loading screens, but as you say it would be nice to make directly instantiating faster too, and there's definitely room for improvement in places

On develop branch I've removed the coroutines in DiContainer and also started moving towards doing much less memory allocs during Resolve.  Ideally, if you called Resolve to get an instance that has already been instantiating then it should execute zero memory allocs.  And similarly with ResolveAll except the alloc for the returned list.   I think this is pretty important since Resolve can be executed after initialization at runtime sometimes so should be optimized better.

But I haven't gotten very far yet in the time I've had to look at this stuff so any help is appreciated.  I'm going to try playing with your benchmark test to see if I can learn more about where the bottlenecks are.  I'll let you know if I know more.  Feel free to chat with me on Gitter as well if you need an explanation for anything (username svermeulen)

**Comment by marsermd** [comment]
Closing issue because expected work was done. Will create a new if needed.
