### ISSUE TITLE
Unity Dll.

### ISSUE THREAD

**Issue by GennadiyHieber** [ssannandeji/Zenject-2019#438]
Hello,
I'm using your framework in my project. Now I need to use it as a DLL, but after creating a build for Unity editor Inject attributes in MonoBehaviour scripts are broken. Also can't understand which keys should be used to build library for target platfroms. Could you assist on it, please?

**Comment by GennadiyHieber** [comment]
Hello,
my previous questions about DLL are still actual. Looking forward to your reply. 
Need your help on this issue, or at least a tip on what can be done to solve this on my own.

**Comment by svermeulen** [comment]
Zenject doesn't support using it as a dll for Unity right now.  But since I've heard this request from a bunch of people I've started working on adding support for this for zenject 6.  I'll close this item once that is working.

If you can't wait for that, you might be able to get away with just extracting the contents of Zenject/Source/Usage directory into a dll, unless you also need to write installers in your own dlls outside of unity too.  More discussion about that in #398

**Comment by GennadiyHieber** [comment]
Thanks a lot for your reply and additional info. 
Is it possible to give an approximate ETA for Zenject 6 support?

**Comment by svermeulen** [comment]
Official release will be in early may and should include DLL support

**Comment by svermeulen** [comment]
Fixed in zenject 6 on develop branch

**Comment by tnelling** [comment]
Is this fixed in the Zenject 6 release? I don't see anything about it in the release notes.

**Comment by svermeulen** [comment]
Yes it should be in Zenject 6.  The part of the release notes related here is this:
```
Added ability to use [Inject], IInitializable, etc. from within custom user DLLs by referencing Zenject-Usage.dll
```
