### ISSUE TITLE
Readme contains outdated info about DiContainer.Instantiate usage

### ISSUE THREAD

**Issue by maxstar** [ssannandeji/Zenject-2019#44]
While I was following the readme and tried to create a custom factory with manual instantiation of objects I found out that Instantiate method is not there.
Checked file history. It seems that it is now called InstantiateInternal and it is not public. There is InstantiateExplicit method but there are no examples on how to use it (using it like described in readme doesn't work).

**Comment by svermeulen** [comment]
The Instantiate method can be found in the InstantiatorExtensions class (it's an extension method on the IInstantiator interface).  So it should work the same way it's used in the README.  Here's a breakdown of the methods:

Instantiate - Use this to create any non-monobehaviour
InstantiateComponent - Add new monobehaviour to existing game object and fill in its dependencies
InstantiatePrefab - Create a new game object from a prefab and fill in dependencies for all children
InstantiatePrefabForComponent - Same as InstantiatePrefab but returns a component after it's initialized
InstantiateComponentOnNewGameObject - Create a new game object, and add the given component to it, and fill in dependencies

You only need to use InstantiateExplicit if you want to pass in null values, since in those cases it can't derive from the type from the value.  This is why it's often better to use Zenject's Factory<> class which handles this for you.

**Comment by maxstar** [comment]
Thanks for the info.
Before I've read your reply I managed to do the magic with InstantiateExplicit. It looked clunky but worked.
Changed it to InstantiatorExtensions approach that you suggested. 
Just feels a bit weird that I use static class while getting rid of static class usages in my project...

And, well, readme still should be updated.

**Comment by svermeulen** [comment]
Oh, you shouldn't refer to the `InstantiatorExtensions` class directly.  It's full of extension methods, so you should be able to call those methods as if they are methods on DiContainer.  So the following should work instead:

```
Container.Instantiate<MyClass>();
```

**Comment by maxstar** [comment]
Ok, I understood what's wrong.
Firstly, I don't have professional knowledge of C# and I didn't know that such thing as "Extension Methods" even exists (C# manual cleared that up for me).
Secondly, as stated in the manual, in order for extension methods to work, you HAVE TO include the namespace they are in with "using". The thing is, I used all Zenject stuff by prefixing it with "Zenject." and never included a namespace, so when I tried to use Instantiate() directly on DiContainer it didn't work. "using Zenject;" put everything where it needs to be.

The road was a bit rough, but I learned new stuff in the end :)
Probably you should add a note to the readme that in order for Instantiate() (or other extension methods) to work as described, you MUST include Zenject with "using" statement.

**Comment by svermeulen** [comment]
Ah yes, hadn't considered that "gotcha" with extension methods being hidden like that.  I'll either add a note to the readme or move the methods directly on to the interface to avoid anyone else experiencing it.
