### ISSUE TITLE
IValidatable is validated multiple times

### ISSUE THREAD

**Issue by Nezz** [ssannandeji/Zenject-2019#452]
Consider the following binding:
```
Container.BindInterfacesTo<Foo>().AsSingle();
```
with the class
```
public class Foo : IFoo, IValidatable
```

The `DiContainer.ValidateValidatables()` method will validate it once for each binding because it performs the validation if the instance type derives from `IValidatable`. See:
https://github.com/modesttree/Zenject/blob/2b0079ef578af03dd484be25bbfedd114411b2b4/UnityProject/Assets/Plugins/Zenject/Source/Main/DiContainer.cs#L267-L273

This will cause the validation to run for each binding. For example if `Foo` also implements `IInitializable`, the validation is executed three times:
```
Validate
Validate
Validate
All scenes validated successfully
```

**Comment by svermeulen** [comment]
You're right.  What it should do is just call `ResolveAll<IValidatable>` to get the IValidatable classes rather than what it's doing now.  That should be easy enough to fix, we'd just need to make sure the current IValidatable classes get bound now.  And then IValidatable could be used by users and not just internal to zenject.

**Comment by svermeulen** [comment]
I took a deeper dive into this.  I realized that looking up the validatables by using `ResolveAll<IValidatable>` won't really work, because that does not include bindings with conditions or identifiers.

The first thing that happens during validation is that the initial object graph is constructed using mostly dummy objects.  Except in cases where classes derive from IValidatable or have [ZenjectAllowDuringValidation] - in those cases the type will actually be instantiated.

How the IValidatable stuff works now (on develop branch) is that during this first phase it builds up a list of all objects that derive from IValidatable, and then as a separate step calls Validate() on each of those.  I found that it's also important to call Validate as a separate step rather than in the middle of object graph construction to avoid causing circular ref errors

The main purpose of IValidatable is to ensure that all objects graphs are constructed, which is why factories and memory pools implement IValidatable and then call Container.Instantiate with the type they are creating.  But it could also be used for custom validation logic too
