### ISSUE TITLE
An easier way to setup the ITickables?

### ISSUE THREAD

**Issue by marsermd** [ssannandeji/Zenject-2019#486]
We make heavy use of ITickables. It's a wonderful feature, but the design of them in the SubContainers looks a bit off.
This is what I'm going to describe below:
1. The current state as I understand it.
2. Cons
3. Pros
4. Possible solutions

Also I'm going to write about `ITickable`, but it's the same with `IInitializable`, etc.

# Current State
When using an ITickable inside a GameObjectContext's container, everything works out of the box: the kernel that is responsible for updating the `ITickables` is automatically created.

Inside a SubContainer which is created via `FromSubContainerResolve` on the other hand, this doesn't happen.
Instead you should pass the `Kernel` in the upper container like so:
```
public class TestInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.BindInterfacesAndSelfTo<Kernel>().FromSubContainerResolve().ByMethod(InstallFoo).AsSingle();
    }

    void InstallFoo(DiContainer subContainer)
    {
        subContainer.Bind<Kernel>().AsSingle();
        subContainer.Bind<Foo>().AsSingle();
    }
}
```
And if you want to pass some kind of facade from the subcontainer, there is only one way to do it: derive  facade from the `Kernel` :
```
public class Foo: Kernel
{
   ...
}
public class TestInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.BindInterfacesAndSelfTo<Foo>().FromSubContainerResolve().ByMethod(InstallFoo).AsSingle();
    }

    void InstallFoo(DiContainer subContainer)
    {
        subContainer.Bind<Foo>().AsSingle();
    }
}
```
This deriving is forced because you can resolve only one instance from the subcontainer.

# Cons
### Single responsibility principle. 
Kernel functionality is forced inside the Facade.

Consider having two facades: `Foo` and `Bar`, where `Foo` derives from `Bar`.
If I want `Foo` to be `ITickable`, I will have to derive `Bar` from `Kernel`.
An alternative would be to implement the `Kernel` functionality inside `Foo` which means code duplication.

### Setup
It is quite easy to have an `ITickable` that is not updated at all. Just forget passing up the `Kernel` somewhere in the subcontainers hierarchy.

# Pros
It is very hard to have an `ITickable` that get's updated twice per frame. I.e. one `ITickable` that's bound in multiple containers with a Kernel in each.
For that you'd have to use something like `FromComponentInParents`. And probably there are even some checks so even that might not work.

# Solutions
###  .WithKernel
```
public class TestInstaller : MonoInstaller
{
    public override void InstallBindings()
    {
        Container.BindInterfacesAndSelfTo<Foo>().FromSubContainerResolve().WithKernel().ByMethod(InstallGreeter).AsSingle();
    }

    void InstallFoo(DiContainer subContainer)
    {
        subContainer.Bind<Foo>().AsSingle();
    }
}
```
Where "WithKernel" adds a bind to Kernel and removes binds from `ITickable` to `Foo`.

### Automation
Probably this can be automated:
If there is bind from `ITickable`, a `Kernel` is automatically bound. And each container tries resolving a `Kernel` from the subcontainers.

This will fail to work with the factories though. So maybe a factory bind should also cause a `Kernel` creation?
But this might lead to performance problems.

# The End
So what do you think?

**Comment by svermeulen** [comment]
Yeah I agree, there's definitely room for improvement here.  I'll respond with more thoughts later but just wanted to mention that another approach would be for us to add `ByNewGameObjectInstaller` and `ByNewGameObjectMethod` (similar to the `ByNewPrefabInstaller` / `ByNewPrefabMethod` which already exist) and which would create a new game object (with GameObjectContext attached).  That would make adding a kernel unnecessary for that case.  That might be nice also because if you are using things like `FromNewPrefab` and `FromNewComponentOnNewGameObject` inside the subcontainer then you can guarantee that those objects will be destroyed when the GameObjectContext is destroyed since by default they will be parented to the GameObjectContext.

But I think we should also clean up the way Kernel works to address what you're saying as well, and let people use whichever approach they want

**Comment by svermeulen** [comment]
Ok I've added the WithKernel method to the LTS branch.  So we can now use facades as strictly a way of delegating calls to other subcontainer classes rather than also doing the ticking / initializing / etc.

Which only exists when using ByInstaller or ByMethod bind methods with FromSubContainerResolve

I also added WithDefaultGameObjectParent which you can use with ByInstaller and ByMethod too, which will ensure that any instantiated game objects get parented underneath it and properly deleted when the subcontainer gets disposed of

**Comment by marsermd** [comment]
That sounds great!

**Comment by svermeulen** [comment]
I've also added ByNewGameObjectInstaller and ByNewGameObjectMethod as another alternative to this problem, so I think that covers this issue
