### ISSUE TITLE
Error at project Upgrade

### ISSUE THREAD

**Issue by aldiazj** [ssannandeji/Zenject-2019#670]
I recently Upgraded my project to Unity 2019.2.11f

And I'm having this error:

`Assets\Plugins\Zenject\Source\Binding\Binders\Factory\FactoryFromBinder\FactoryFromBinder4.cs(23,13): error CS0433: The type 'Func<TArg1, TArg2, TArg3, TArg4, TArg5, TResult>' exists in both 'Unity.Compat, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

Any idea how to solve it? I'm using Zenject 8.0.0

**Comment by Mathijs-Bakker** [comment]
¡Hola!
I really don't know. 
Oh wait! this is an old and obsolete fork of Zenject.
The Zenject releases you find here are not maintained since 1,5 year or so.
Better get the most recent one here: [GitHub - Extenject Release 9.1.0](https://github.com/svermeulen/Extenject/releases)
 Or in the [Unity Asset Store](https://assetstore.unity.com/packages/tools/utilities/extenject-dependency-injection-ioc-157735)

Saludos!

**Comment by aldiazj** [comment]
Thanks for your answer, I imported that version from the asset store but still got the same error

**Comment by aldiazj** [comment]
Ah Forget it, It was an issue with firebase sdk, thanks!

**Comment by aldiazj** [comment]
I needed to update firebase to the .Net4x version
