### ISSUE TITLE
Missing usage example for Signals in README.md

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#75]
By reading the documentation, I see how to bind a signal but I still cannot understand how the signal is used by the user's classes.

**Comment by green-coder** [comment]
In the same topic, I wonder why the generic parameter's order is the opposite as the function name imply:

``` csharp
Container.BindSignalTrigger<GameLoadedSignal.Trigger, GameLoadedSignal>()
```

Shouldn't it be called `BindTriggerSignal` instead?

**Comment by svermeulen** [comment]
I called it `BindSignalTrigger` because any conditionals that you add afterwards are applied to the trigger, not the signal.

For example, after adding this:

```
Container.BindSignalTrigger<GameLoadedSignal.Trigger, GameLoadedSignal>().WhenInjectedInto<Foo>();
```

The `GameLoadedSignal` will be accessible anywhere but the `GameLoadedSignal.Trigger` will only be accessible from `Foo`.

So it's like you're binding the trigger, with the signal automatically being bound as well as a secondary operation.

You're right that the ordering of the generic arguments could still have matched though  :)  Probably not worth breaking it for people though now.

**Comment by green-coder** [comment]
Backward compatibility is important, but it shouldn't stop you from fixing confusing wording in your API. I suggest that you provide a clearer alternate function name and mark the current one as deprecated.

How about renaming the function `BindTriggerToSignal<MyTrigger, MySignal>()`? It sounds like `Bind<MyTrigger>().To<MySignal>().WhenInjectedInto<Qux>()` which would be consistent with the existing `Bind<IFoo>().ToXXX<Foo>().WhenInjectedInto<Qux>()` w.r.t. the condition on the binding of the trigger.

**Comment by green-coder** [comment]
I have some doubts about the current design of the injection of the trigger/signals: _IMHO_, the injection of the **signal** should be subject to conditional expressions, so that objects can receive signals triggered by different sources.

**Comment by svermeulen** [comment]
Yeah I know what you mean.  Ideally, you would be able to specify conditionals on both.  If you look at the BindSignalTrigger method, this is all it's doing:

```
        container.Bind<TSignal>().ToSingle();
        container.Bind<Signal>().ToSingle<TSignal>().WhenInjectedInto<TTrigger>();
        return container.Bind<TTrigger>().ToSingle();
```

It only returns the ToSingle() call for the trigger.  The line with `container.Bind<TSignal>().ToSingle();` returns conditionals for the signal but they are not provided to the calling class at all.

I'm open to suggestions on this if anyone has some better ideas.  Renaming it to BindTriggerToSignal sounds reasonable to me too.  I didn't call it that because technically it's using a different definition of "Bind".  In all other cases, "Bind" refers to associating an interface or a parent class with a concrete class.  But the consistency with what you're suggesting is kinda nice.

**Comment by green-coder** [comment]
To simplify, how about getting rid of the Trigger class and only use the signal class for listening events and firing them? Injecting the signals would become a normal injection operation without the need to have any dedicated extension function.

**Comment by svermeulen** [comment]
That would simplify the binding, but I actually like having the triggering separate from the listening.  Otherwise, it's no different from just passing around a class like this:

```
class MySignal
{
    public Action Event = delegate {};
}
```

Or even just using a global like this:

```
static class MySignal
{
    public static Action Event = delegate {};
}
```

Where anyone can both trigger the event and observe the event.

I find in most cases, I don't really care about restricting access to observing the signal, but I often do want to restrict access to the trigger to certain classes - often just one class.

For eg. in a MVC app, you often have code in the model layer triggering events that are observed by the controller layer, etc.  So this way you can make sure that the controller layer never triggers any model events.

I agree that it could be more elegant though, and that it would still be useful to be able to control access to the signal.  I'll think about it some more.

**Comment by svermeulen** [comment]
What about just splitting up the signal bind and the trigger bind into separate statements?  Like this:

```
Container.BindSignal<SomethingHappenedSignal>()
    .WhenInjectedInto<Bar>();

Container.BindTrigger<SomethingHappenedSignal.Trigger>()
    .WhenInjectedInto<Foo>();
```

**Comment by green-coder** [comment]
Yes, I think it would be better like that as you do not make assumption about how the user is going to use it and for which use case.

Independently, I am wondering if there is a way with C# to let the user create his `MySignal` subclass without having to write an empty inner class for the trigger.

**Comment by svermeulen** [comment]
Yeah I think that's better too.  I made the change on develop branch, going to wait a few days then make a new release with it after I update the documentation

**Comment by Zexbe** [comment]
@green-coder would something like Trigger<MySignal> fit that use?

**Comment by green-coder** [comment]
@JoshFisk : Yes, I think this is an elegant and convenient solution.

**Comment by svermeulen** [comment]
Somehow making it work with `Trigger<MySignal>` is an interesting thought, but I'm not sure how to do that without also making Signals triggerable by any class, and therefore defeating the purpose of having a Trigger class in the first place.  There might be a clever way of doing that though.  For now I'll leave it as is

I've added a release with the other changes discussed here, and also updated the documentation to address the original issue.

**Comment by Zexbe** [comment]
@svermeulen I have created a new issue, with an example on how to make a generic trigger, without a signal being triggerrable directly.

**Comment by svermeulen** [comment]
Ok I'll take a look - thanks.  I'm open to taking this approach.  Forcing people to add an empty class does feel a bit clunky.

**Comment by svermeulen** [comment]
Ok well for some reason the new issue that you created has vanished... Seemed to have happened after I referred to it here in [this commit](https://github.com/modesttree/Zenject/commit/e615e5394955dba92cb23aff4bdd2a3263f11ab6).  Github bug maybe?  I certainly didn't delete it.

Anyway, I'll just post my comments here instead.

Interesting idea!  Adding a generic argument for the derived class would address that problem

This new solution would look very similar to the current method, seems to me the only difference would be:

```
public class SomethingHappenedSignal : Signal<SomethingHappenedSignal, string, int, float>
{
}

public void InstallBindings()
{
    Container.BindSignal<SomethingHappenedSignal, string, int, float>();
    Container.BindTrigger<SomethingHappenedSignal, string, int, float>();
}
```

Compared to how it is currently:

```
public class SomethingHappenedSignal : Signal<string, int, float>
{
    public class Trigger : TriggerBase { }
}

public void InstallBindings()
{
    Container.BindSignal<SomethingHappenedSignal, string, int, float>();
    Container.BindTrigger<SomethingHappenedSignal.Trigger, string, int, float>();
}
```

Usage would be the same in both cases and would look like this

```
public class Foo
{
    readonly SomethingHappenedSignal.Trigger _trigger;

    public Foo(SomethingHappenedSignal.Trigger trigger)
    {
        _trigger = trigger;
    }

    public void DoSomething()
    {
        _trigger.Fire(...);
    }
}
```

Pros:
- You don't have to add an empty trigger class

Cons:
- You have to include the derived class in the base class generic arguments
- The implementation seems a bit too clever
- May add additional headache when used with AOT platforms like iOS / WebGL since it does do some magic with generics - might also be ok, not sure
- It's not really clear to the user that the `SomethingHappenedSignal.Trigger` class exists at all, since it's not included in the binding or the class declaration.  
- There's nothing stopping the user from using the base trigger class directly which would be pretty ugly (`Signal<MySignal, float, int, string>.Trigger`)
- It's another breaking change though that's not a huge deal since I only just broke it anyway

So I'm kinda leaning towards keeping the current approach.

If you want to play with this new approach, I implemented it anyway and pushed it to the `SignalAlternative` branch

**Comment by Zexbe** [comment]
I closed the issue after I noticed a commit, my bad. I think the original is better as well. The first con can be mitigated slightly by adding a generic constraint that forces it to be a signal.

**Comment by svermeulen** [comment]
That's odd - I wasn't seeing that issue you created listed in Closed or Open at all for some reason.  Yet now it is showing up... Ah well.  

Alright thanks - It was worth considering.

**Comment by green-coder** [comment]
@svermeulen  Remember that the user of the library is someone who want to build games, not destroy them. It is not as if this library was used in a critical system for a bank.

**Comment by green-coder** [comment]
Would it be possible to change this:

``` csharp
public void InstallBindings()
{
    Container.BindSignal<SomethingHappenedSignal, string, int, float>();
    Container.BindTrigger<SomethingHappenedSignal, string, int, float>();
}
```

into this?

``` csharp
public void InstallBindings()
{
    Container.BindSignal<SomethingHappenedSignal>();
    //Container.BindTrigger<SomethingHappenedSignal>();
    Container.BindTrigger<SomethingHappenedSignal.Trigger>();
}
```

**Comment by svermeulen** [comment]
This would be cool - I will check it out

**Comment by svermeulen** [comment]
This turned out be a trivial change... Good catch!

I've pushed this to develop branch and will merge it in soon.

**Comment by green-coder** [comment]
It might seem crazy, but I think that we should just get rid of `Container.BindSignal()` and `Container.BindTrigger()` : they don't bring any conveniency and they inforce the `.ToSingle()` use case.

I would be in favor of adding some sample use cases in the documentation for binding signals and triggers instead.

**Comment by Zexbe** [comment]
@green-coder 

I'm not sure that would work. Here are a few issues that I think would come up.
1. The Trigger, and Signal class are designed to work as singletons.
2. The Trigger class has it's Signal class injected
3. The Signal/Trigger is implemented as an extension, I'm not sure how it would tap into the normal binding.

**Comment by svermeulen** [comment]
Yeah, Josh's second point is the main reason for this.  The Signal has to be a singleton so that it can be injected into the Trigger.  Also, I'm not sure what the use case would be for making them a non-singleton.

That did make me realize something though:  The bind commands for signals/triggers do not support identifiers.

I've fixed this in develop so it's now consistent with everything else (that is, it allows an optional identifier).   See `TestSignalsWithIdentifiers.cs` for example of how this would be used.

**Comment by green-coder** [comment]
The use case for a non-singleton signal was for different objects to communicate inside an complex object instantiated multiple times. However, this use case disappear when we use a sub-container for the complex object, as inside this sub-container the signal is a singleton.

I really love the sub-containers and I hope to use them more and more often.
