### ISSUE TITLE
How to resolve new instance of transient type and pass in argument?

### ISSUE THREAD

**Issue by rotorz** [ssannandeji/Zenject-2019#9]
I am trying to figure out how I would inject two specific instances into a new instance of my `SpecialPurchaseMethodProcessor` class along with regular injected arguments.

``` csharp
public class DefaultPurchaseMethodProcessorFactory : IPurchaseMethodProcessorFactory {
    ...
    private DiContainer _container;
    private Dictionary<Type, Func<IPurchaseMethodProcessor>> _creators;

    public void Bind<TPurchaseMethod, TPurchaseMethodProcessor>()
        where TPurchaseMethod : IPurchaseMethod
        where TPurchaseMethodProcessor : IPurchaseMethodProcessor
    {
        _creators[typeof(TPurchaseMethod)] = () => _container.Resolve<TPurchaseMethodProcessor>();
    }

    public IPurchaseMethodProcessor CreateProcessor(IPurchasableItem item, IPurchaseMethod method) {
        var creator = _creators[item.GetType()];
        return creator();
    }
}

public sealed class SpecialPurchaseMethodProcessor : IPurchaseMethodProcessor {
    public SpecialPurchaseMethodProcessor(
        // Specific item for which to create processor for:
            IPurchasableItem item,
            IPurchaseMethod method,
        // Injected types as normal:
            IVirtualCurrencyManager currencies
    ) {
        ...
    }
    ...
}
```

So this would be consumed as follows:

``` csharp
var processor = factory.CreateProcessor(jellyBeansItem, virtualCurrencyPurchaseMethod);
if (processor.CanPurchase)
    processor.InitiatePurchase();
```

Does Zenject provide a way to solve this problem? or am I just going about this in the wrong way?

**Comment by rotorz** [comment]
I mean, I could just use the following approach:

``` csharp
public sealed class SpecialPurchaseMethodProcessor : IPurchaseMethodProcessor {
    public sealed class Creator : IPurchaseMethodCreator {
        public Creator(
            IVirtualCurrencyManager currencies
        ) {
            _currencies = currencies;
        }

        private IVirtualCurrencyManager _currencies;

        public IPurchaseMethodCreator CreateInstance(IPurchasableItem item, IPurchaseMethod method) {
            return new SpecialPurchaseMethodProcessor (item, method, _currencies);
        }
    }

    ...
```

With something like:

``` csharp
factory.Bind<VirtualCurrencyPurchaseMethod, SpecialPurchaseMethodProcessor.Creator>();
```

I am just curious as to whether Zenject provides a different solution to this problem :)

**Comment by svermeulen** [comment]
Great question.  There is a standard way of doing this in Zenject - I will elaborate later today.

**Comment by svermeulen** [comment]
The way I recommend doing it is as follows:

```
public sealed class SpecialPurchaseMethodProcessor : IPurchaseMethodProcessor 
{
    public SpecialPurchaseMethodProcessor(
            // Specific item for which to create processor for:
            IPurchasableItem item,
            IPurchaseMethod method,
            // Injected types as normal:
            IVirtualCurrencyManager currencies)
    {
        ...
    }
    ...
    public class Factory : FactoryTyped<IPurchasableItem, IPurchaseMethod, SpecialPurchaseMethodProcessor>
    {
    }
}
```

Then installing it like so:

```
_container.Bind<SpecialPurchaseMethodProcessor.Factory>().ToSingle()
```

Then any class can declare the `SpecialPurchaseMethodProcessor.Factory` as a dependency and create your `SpecialPurchaseMethodProcessor` without having to worry about the non-dynamic dependencies (such as, in this example, `IVirtualCurrencyManager`).

```
class Foo
{
    SpecialPurchaseMethodProcessor.Factory _processorFactory;

    public Foo(SpecialPurchaseMethodProcessor.Factory processorFactory)
    {
        _processorFactory = processorFactory;
    }

    public void Bar()
    {
        var processor = _processorFactory.Create(item, method);
    }
}
```

There are several other ways to do this (such as passing constructor arguments to `_container.Instantiate<>()`, using `Instantiator.Instantiate`, or using `IFactory<>`) however in my opinion using `FactoryTyped` is by far the best approach.

The convention I use is to define an empty internal class that inherits from `FactoryTyped<>` and provides the required dynamic arguments to it as generic parameters.  I follow the same convention as `Func<>` in that the last generic argument refers to the actual type you want to create, and the ones before it are the parameters.

Another good reason to use `FactoryTyped` is that it is automatically validated.  So if you add a dependency to `SpecialPurchaseMethodProcessor` that isn't installed it will complain during validation instead of runtime.

Also note that if you do decide to go with `FactoryTyped` you'll need to update as I only committed it from our internal branch just now  :)

The documentation hasn't been updated yet for it.

**Comment by rotorz** [comment]
Fantastic stuff, thanks again for the quick response!

I will spend some time experimenting with this today :D

**Comment by rotorz** [comment]
This works great, thanks again for your help :)
