### ISSUE TITLE
Data driven container installer

### ISSUE THREAD

**Issue by green-coder** [ssannandeji/Zenject-2019#92]
I think you are going to think 'wtf??' with this feature request, but I like the idea so here it is:

It would be nice to have something which let the users define the binding in the editor directly, without a need for him to write an installer class, i.e. a "data driven container installer".

**Comment by svermeulen** [comment]
You can partially do this using the [Automatic Bindings Feature](https://github.com/modesttree/Zenject#autobind).  I know it's not exactly what you're proposing but worth a mention

**Comment by green-coder** [comment]
I found a [tool on Unity's AssetStore](https://www.assetstore.unity3d.com/en/#!/content/53742) which does some kind of dependency-related stuffs (like DI but in a weird way). I post the [link to the video](https://www.youtube.com/watch?v=lcqoPOIYMno) here because it contains something remotely close to the feature I requested.

**Comment by svermeulen** [comment]
Personally, I don't like having too much information inside the scene itself.  The best example of this is using component references which can be very brittle (as pointed out by the video you linked to).   Reasons that occur to me:
- It's often really difficult to see what's really going on and what references what etc. since so much of the information in the scene is hidden until you click on the various objects, some of which can be in some deep level in the heirarchy
- It doesn't diff well if you're using source control
- There often isn't very good compile-time checks
- It isn't searchable like code is.  Want to see what references a certain class/type?  You can do a plain text search over your code base or use visual studio intellisense - which you can't really do very easily if that kind of information is in the scene

Having binding information in the scene would suffer similar drawbacks.  So if such a Zenject feature existed, some people might like it but I can't see myself ever really using it

**Comment by green-coder** [comment]
I agree your points. That could be a bad idea for the long run.
