### ISSUE TITLE
[Thought] GlobalCompisitionRoot prefab instead of GlobalInstallerConfig

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#98]
It occurred to me that instead of loading a config asset with the installers, you could instead load a prefab with the `GlobalCmpisitionRoot` object attached and instantiate it? There would be no gain in doing so and nothing you couldn't do already. Mostly just a thought that crossed my mind.

**Comment by svermeulen** [comment]
This wouldn't work though because you can define multiple `GlobalInstallers` assets.  This is helpful if you want to add global installers from different parts of your code base.  Then all these installers get added to one `GlobalCompositionRoot`

**Comment by Soren025** [comment]
I see

**Comment by svermeulen** [comment]
After more thought, I'm starting to think your suggestion of just using a `GlobalCompositionRoot` prefab is better.  Always loading multiple `GlobalInstallers` assets might get annoying since it puts the power in the libraries themselves that contain the `Resources/GlobalInstallers` files.  Really, the DI way is to have one place where the configuration is set, so having just one `GlobalCompositionRoot` makes more sense and is more flexible if you find yourself re-using the same libraries in multiple unity projects.

Also, using a `GlobalCompositionRoot` prefab allows you to actually add game objects to the global composition root directly on to the prefab, rather than having to set up a dynamic binding.

**Comment by svermeulen** [comment]
Fixed
