### ISSUE TITLE
ExecutionOrderInstaller lacking features

### ISSUE THREAD

**Issue by Soren025** [ssannandeji/Zenject-2019#99]
I feel there is some functionality lacking within `ExecutionOrderInstaller`.

For starters from what I can see, it does not bind the priority of `IFixedTickable` and `ILateTickable` within the `BindPriority()` method.

Another feature I feel is lacking is the means of binding only a single callback to a priority. Such that I can have a type's `Initialize()` have a priority of -100 while its `Dispose()` having a priority of 100 for example.

**Comment by svermeulen** [comment]
You're right, we need to add `IFixedTickable` and `ILateTickable` bindings there.

I think the default behaviour of the `BindPriority` method is fine, since this is what you want in most cases (it is also the same behaviour that Unity has when defining a "Script Execution Order" on a MonoBehaviour), but it might also be helpful to be able to specify a priority per-interface.  So maybe we just need add some extra static helper methods for this like `BindInitializablePriority`, `BindTickablePriority`, etc. in addition to just `BindPriority`

**Comment by Soren025** [comment]
Sounds good.

Out of curiosity, as a side note. The `BindPriority()` method "instance binds" a new `Tupple<Type, int>` such that it is injected as a list into the respected manager. Does the lists order reflect the order in which the instance is bound?

For example (with the proposed methods).

``` csharp
ExecutionOrderInstaller.BindPriority<Foo>(Container, -100);
ExecutionOrderInstaller.BindDisposablePriority<Foo>(Container, 100);
```

If I were to do this, my first thought at an expected result is that it would first bind everything at a priority of -100. Following it would override the priority for `IDisposable` as 100.

**Comment by svermeulen** [comment]
Yep, when you bind multiple values to the same type it should result in a list with the order that the bind methods occurred in.  

In this case though that won't work because DisposableManager will still get both priorities, and will most likely throw an exception since it won't know which one to use.  We could change it to support this ability to override but I'm not sure that's better than just requiring that users supply unique priorities

**Comment by Soren025** [comment]
I see.

I am not sure about that either, I can see where it would be useful to throw an error as opposed to tracking down where that one installer that is overriding a priority you need set (assuming you realize it is being overridden).

The benefit of overriding is non existent without single interface priority binding and only really reduces number of lines needed to write with it. (below is the same example above without overriding)

``` csharp
ExecutionOrderInstaller.BindInitializablePriority<Foo>(Container, -100);
ExecutionOrderInstaller.BindTickablePriority<Foo>(Container, -100);
ExecutionOrderInstaller.BindLateTickablePriority<Foo>(Container, -100);
ExecutionOrderInstaller.BindFixedTickablePriority<Foo>(Container, -100);
ExecutionOrderInstaller.BindDisposablePriority<Foo>(Container, 100);
```

**Comment by svermeulen** [comment]
Exactly, yeah, I think just adding those helper methods would be enough for now, since that covers this case anyway, just a bit more verbose

**Comment by Soren025** [comment]
I found some classes that have not been documented in the readme called `FixedTickablePrioritiesInstaller` and `LateTickablePrioritiesInstaller` that do those two callbacks `ExecutionOrderInstaller` does not handle individually outside of `ExecutionOrderInstaller`.

An artifact of something you started and forgot about perhaps?

**Comment by svermeulen** [comment]
Yep, those should be deleted or merged into `ExecutionOrderInstaller`

**Comment by svermeulen** [comment]
Fixed
